---
title: "Not All Same"
author: "DK"
date: "2024-09-26"
draft: yes
categories: [talents]
---

One time, an economics professor stated that despite his original thinking his children are vastly different

I thought he should stick to his area of training.

I learned for myself that each child is different

My parents allowed me to find out who I am without pressure or contstraints I am sure I failed in some areas but I am glad they gave me room to grow and become who I am

Never straying from their teaching

###

Intrinsic worth

Worth of an aluminium

$2000 per ton is the current pricing.

An aluminium reel to reel costs well over $30.
The work of designing, fabricating (machining), testing and marketing, and logistics adds to this cost.
I suppose we could go back to making all things our selves.

###

Importance of labels

Beware of labels

What began as a helpful intended to improve the product and introduce new labelling resulted a massive pushback from the customers.

They had an underlying issues and when the trigger appeared they unloaded.

There was no intrinsic change just the surface change, a unified packaging change, mainly, changes to colors to match the general company-wide initiative.
