---
title: "젊어서고생"
author: "DK"
date: "2024-09-06"
draft: yes
categories: [intro]
---

젊어서고생

젊어서 고생은 사서도 한다

It's okay to go through hardships when you're young.


출처 : 중부매일 - 충청권 대표 뉴스 플랫폼(http://www.jbnews.com)

맹자는 '생어우환 사어안락(生於憂患 死於安樂)'이라 했다. '걱정과 어려움이 나를 살게 하고, 안락함이 나를 죽음으로 이끈다'는 뜻으로

출처 : 중부매일 - 충청권 대표 뉴스 플랫폼(http://www.jbnews.com)

It literally means "people even pay for a hardship in their younger age",

Similar saying, 집 떠나면 고생

http://www.koreatimes.com/article/1427284


When old we seek comfort

Growth comes as we leave the place of comfort
And when young take on hardships.




My dad refused comforts

What has convenience done for us
What is the tradeoff
Not all changes are improvements in my dad’s mind

Mission experience
Forget too soon
Military experience
Almost got killed during dining hall experience

옛 어르신들의 말에 '젊어서 고생은 사서도 한다'는 속담이 있다. 젊은 시절의 고생은 장래 발전을 위해 좋은 경험이 되므로 달게 여기라는 뜻이지만 오늘날 현대를 살아가는 젊은이들이 갈수록 나약해지고 있어 걱정스러운 마음 금할 수 없다.

It is desirable to have 困難 (trials), even purchase challenges, while in youth
Instead of shying away from trials, it will do a person a lot of good to face challenges early in life.

맹자는 '생어우환 사어안락(生於憂患 死於安樂)'이라 했다. '걱정과 어려움이 나를 살게 하고, 안락함이 나를 죽음으로 이끈다'는 뜻으로, 고난에도 좌절하지 말고, 안락할 때 방탕하지 말라는 경계의 말이라고 생각한다.

http://www.jbnews.com/news/articleView.html?idxno=1360159

Founder of Mitsubishi

