---
title: "Intrinsic Human Dignity"
author: "DK"
date: "2024-11-21"
draft: yes
categories: [dignity]
---

The guiding light of our community and the most esteemed rabbi ever to teach at Yeshiva University was Rabbi Joseph B. Soloveitchik of blessed memory. He was the scion of one of the most revered rabbinic families in all of Jewish history. He was a master of Talmud and secular knowledge, and his students and legacy animate our institution. He once said:

*I may have very few good traits, but one trait which I do possess is my inability to imitate anyone else. I always want to be myself and to display my unique dignity of having been created in the image of God. The glory of the individual is exemplified by the singularity of every human being. This concept is the motto of my life. . . .*

*. . . I do not like to do what others can do better or just as well. I wish to do that which I am unique at! This is not an expression of haughtiness; no, it is a fulfillment of my intrinsic human dignity and individuality.*^[7. Joseph B. Soloveitchik, “21.02 Yeshiva University I,” in Aaron Rakeffet-Rothkoff, [*The Rav: The World of Rabbi Joseph B. Soloveitchik*](https://ktav.com/products/the-rav-1)*,* vol. 2, ed. Joseph Epstein (Brooklyn, New York: KTAV Publishing House, 1999), 225–26.]

Human struggle with life,

Reflected in singing. Not imitate but find your own range
