---
title: "Hey Bishop"
author: "DK"
date: "2023-10-15"
draft: yes
categories: [intro]
---

가사

사랑을 위하여 김종환

이른 아침에 잠에서 깨어 너를 바라 볼 수 있다면 물안개 피는 강가에 서서 작은 미소로 너를 부르리 하루를 살아도 행복 할 수 있다면 나는 그 길을 택하고 싶다 세상이 우리를 힘들게 하여도 우리 둘은 변하지 않아 너를 사랑하기에 저 하늘 끝에 마지막 남은 진실 하나로 오래 두어도 진정 변하지 않는 사랑으로 남게 해주오 내가 아플때보다 니가 아파할때가 내 가슴을 철들게 했고 너의 사랑앞에 나는 옷을 벗었다 거짓의 옷을 벗어 버렸다 너를 사랑하기에 저 하늘 끝에 마지막 남은 진실 하나로 오래 두어도 진정 변하지 않는 사랑으로 남게 해주오 너를 사랑하기에 저 하늘 끝에 마지막 남은 진실 하나로 오래 두어도 진정 변하지 않는 사랑으로 남게 해주오 사랑으로 남게 해주오

At a certain juncture people’s preference of music transitions from popular music to soul music. The music that not only entertains but touches and moves the soul.

The transition point is age independent but rather exposure or experience dependent.

Soul music speaks to and about life’s common experience, and often – its struggles.

As Ella Wheeler Wilcox wrote in Solitude

“Laugh and the World laughs with you, Weep, and you weep alone…”

Happy sounds, pervaded by popular songs are universally liked and followed.

Deep anguish and sorrow conveyed in the lyrics of soulful music seems to be almost hidden from society - unpopular.

However, they are felt deeply and widely and followed by the masses – quietly yet purposefully.

Many of them have traveled more than halfway to their destinations in life or have experiences that qualify them for that group.

Present day cultures does not promote or recognize suffering, to the same degree as achievements and triumphs.

However, for me, if I am feeling sad, I feel better by singing a soulful song rather than a cheerful, popular song.

One feels comforted and healed.

Why is that so?

Feel better by commiserating.

Elements of a Soulful Song

Limitations and seeming cruelties of life.

Whether it be love, both expressed and unexpressed.

Life’s pursuit, achieved or given up.

Memories kept and almost rekindled

Soulful songs deal with disappointments rather thaforn successes, for the most part.

A Hope the future. Despite challenges and a right to be despondent, the song echoes a hope for the future.

Together, with love, and help from Above, we can overcome present day sadness and be victorious.

Life’s lessons learned from small things Observes small actions, slight touches. Soulful artists are impressionistic, capturing those images for the rest of us. Putting words and music to those moments that we want to capture and remember

Song ages better than almost anything Song improves over the years and new meanings are generated or created.

Lyrics are easy to understand at first but the meaning changes over time It is very difficult to translate into another language, either keep the rhythm or invent new phrases to capture the full meaning.

Sad melodies and lyrics create an environment Remember the times, place and person. Popular music does this as well. Soul music does it more efficiently.

Able to bring to mind the feelings of first love, lost ones, with an opening line.

“이른 아침에 잠에서 깨어, 너를 바라 볼 수 있다면”

Is an opening line from 사랑을 위하여 by Korean crooner, 김종환

If I am privileged to see, the first thing in the early morning, is you.

And other lines such as,

내가 아플때보다 니가 아파할때가, 내 가슴을 철들게 했고

I learned to empathize and grew from your suffering rather than mine.

And finally

오래 두어도 진정 변하지 않는, 사랑으로 남게 해주오

The kind of love that endures through ages, let that be ours.

Soulful music stretches the vocal range of singers, musically representing the struggles of listeners.

As the singer’s voice struggles, and almost cracks, a new level of sound is achieved and appreciated.

These song can be enjoyed, passively.

To enjoy maximally, take a live recording, or a K-Oke Version if you prefer, take it to a quiet place (for the sake of others), put it on a loop mode, and sing along until you can’t sing no more or you feel better.

Mistake and all,

It will be the most satisfying performance.

That is what I intend to do all week long.

------------------------------------------------------------------------

Beatles sang,

Hey you've got to hide your love away
