---
title: "Untitled"
---

**0:00**

when camela Harris was Camala Harris was talking about Equity she either didn't

**0:05**

know what she was talking about which is inexcusable or she knew what she was talking about which was malevolent those

**0:13**

are the options it's like they just mean equality of opportunity it's like then why do they have a different word they

**0:20**

don't mean equality of opportunity they mean equality of outcome if you're foolish enough to believe in equality of

**0:25**

outcome then you deserve to lose the Senate lose the house and lose the

**0:31**

presidency right and that's what happened that's

**0:37**

that American Dream element that that admiration for entrepreneurial

**0:43**

Excellence that while you see that manifested in someone like Elon Musk and you know two thumbs up for that as far

**0:50**

as I'm concerned and it would be lovely especially over the next four years if all you entrepreneurial types stop

**0:56**

letting the radical progressives have the moral upper hand because they for the poor it's like no they're not not a

**1:03**

not even a bit all the bloody green leftists have done in Europe is doomed the poor to extensive and deteriorating

**1:10**

poverty that's all they've done they haven't cleaned up the environment one bit they would musk jump the board I

**1:16**

thought oh if musk would do something like establish a a department of

**1:21**

governmental efficiency I would support Trump just for that like just that but that's not

**1:27**

all he's got I think Gabbert is great she's very very solid she's the candidate the Democrats should have run

**1:33**

this is an appalling fact if Biden would have been willing to give Trump some credit which he should have because Mr

**1:39**

Trump might have just ridden off into the sunset If he if they had been willing to give the devil is due you

**1:46**

know he should have got the Nobel Peace Prize for those Abraham Accords if someone just meet you on an elevator and

**1:51**

says what do you do how do you

**1:57**

respond um I off often tell them to look up my name but to beware of doing so

**2:04**

that's a good answer that is a really good answer uh so what is the best thing

**2:11**

and the worst thing about being Jordan Peterson well I I suppose the worst

**2:18**

thing probably is that I can't I'm I'm quite a lot of trouble all things considered um I'm

**2:26**

troubled to my wife I'm troubled to me I'm troubled to be around and so maybe that's the worst thing it's complicated

**2:33**

um the best thing is unlimited opportunity right yeah it's

**2:39**

it's it's it's absurd fundamentally that's great it's ridiculous it's ridiculously great and

**2:46**

well so I have a question here how do you decide who gets your time what gets your time how and how do you politely

**2:52**

say no to set boundaries because it's got to be all these opportunities there's opportunity cost right with

**2:58**

opportunities so you have to spend that time well there there's a variety of ways of doing that and you have to build

**3:04**

you as your wealth of opportunities increases the infrastructure that you have around you to deal with the

**3:11**

opportunities also has to expand and so there's a variety of ways that you

**3:17**

decide what gets your time when you have more opportunities than you know what to do with and first thing you have to do

**3:24**

is figure out what your priorities are right so you need a vision for the future that's welldeveloped and then you

**3:29**

have to see if the opportunities that you're being presented with are in keeping with what it is that you're

**3:35**

trying to achieve and that should be very well delineated then I have a lot

**3:42**

of people who help me with that you know I'm surrounded I wouldn't call them Gatekeepers exactly because that's not

**3:49**

right the right way of conceptualizing them I have a variety of people around me who help me negotiate and who

**3:56**

prioritize potential opportunities for me and there people who know why I'm

**4:01**

doing what I'm doing and who are on board with that and so when they're making decisions I can be confident that

**4:07**

they're bringing to my attention and prioritizing opportunities that further the broader Mission and then I suppose

**4:17**

that I also use money because money is the way that we negotiate priority and

**4:23**

so and and it's a very efficient way of doing that if I have two opportunities that look like they're of equal value

**4:30**

with regard to the relevance to my aims and one pays twice as much well it's obvious which one to take and that's

**4:37**

partly why we use money right because money is a universal representation system for value and it can't it's not

**4:45**

perfect because it doesn't fully capture potential opportunity right it's

**4:51**

like when you're trying to value a company you can value the company with regards to its current earnings or its

**4:56**

profit margin but you also have to factor in growth and that's a difficult thing to do and so if I'm trying to

**5:02**

prioritize opportunities the financial return is obviously relevant but the

**5:08**

possibility for growth coming out of the opportunity is also now that's more

**5:13**

difficult to quantify but that's also why I have lots of people around me who help me with that and like I have lots of people around me who who do this for

**5:20**

me there's probably altogether All Things Considered there's at least 15

**5:26**

people uh there's probably more like 30 who are doing this for me all the time

**5:31**

and so all the opportunities that do end up on my desk so to speak have been vetted extraordinarily thoroughly and

**5:38**

they're almost inevitably worth further Pursuit but

**5:46**

so if you're overwhelmed by your responsibilities and your opportunities

**5:52**

part of the reason for that is that you haven't distributed enough responsibility to other people you

**5:58**

haven't set up a team that's of sufficient quality and then you have to

**6:04**

ask yourself why you know one possible reason might be that you're

**6:10**

not brutal enough to make the hard decisions that are necessary with

**6:16**

regards to Staffing so for example I've been running a tour now

**6:23**

for8 years I guess 8 years and we're

**6:28**

very cutting dried with regards to our touring Staffing we have very stringent

**6:34**

rules and the one rule for example is don't bother the people who come and see

**6:40**

me you are obligated to be 100% polite

**6:46**

to them under all circumstances all the time and that goes as well for I travel

**6:52**

with some security guys for example and they help me with Logistics and like they have to be good to the waiters and

**6:58**

to all the service staff that we encounter like I want to travel to the places I'm going leaving nothing but a

**7:05**

good taste behind and this is something very important to consider if you're running any kind kind of business

**7:11**

especially as you become more successful because if people have a certain degree

**7:16**

of admiration for you let's say or you're even willing to meet you halfway and then you disappoint them they will

**7:23**

never forget that and they will tell like a thousand people and you don't have to make many mistakes like that

**7:29**

till gets around and things are not good and so our policy especially on the

**7:34**

tours is you don't make mistakes if you make mistakes we you don't come along

**7:39**

and now I shouldn't exactly say that because people are going to make mistakes they have to fix them right I

**7:46**

mean things are going to slip a sideways from time to time but you have to fix it

**7:51**

and and you you have to treat everyone well and that's our criteria for that

**7:57**

are very strict and stringent and that's the case for all the Staffing and hiring decisions that we make and because of

**8:05**

that I I'm surrounded by people that I can really trust and they have their things to do and I leave them alone so

**8:12**

that's another thing you know if you if you're overwhelmed with responsibility and opportunity you got to ask yourself

**8:17**

if you're trying to control too much and you might think well I want to pay every

**8:22**

attention to every little detail it's like no you don't no you don't you want

**8:28**

to use your time which is rare so that you focus on

**8:34**

those things that only you can do and that you do best and everything else

**8:39**

that anyone else could do that should be distributed down to them and so and you

**8:44**

can do that if you're willing to be picky in your hiring and your and your

**8:51**

uh what would you say your willingness to maintain people over the long run if

**8:57**

you're picky in that about that then you can just distribute responsibility and the huge advantage to that is then you

**9:02**

get to focus on what you're best at and what you find that's most compelling and you get get to further your aims and

**9:09**

there's no loss in that and it also stops you from getting worn out and it stops you from getting resentful and you

**9:15**

don't want to get worn out because then you do stupid things and you die and you don't want to get resentful because then

**9:21**

you're miserable to yourself and everyone else and so you you maximize the opportunity

**9:28**

that's in front of You by building an efficient infrastructure and then you shouldn't be overworked you know you got

**9:34**

to also ask yourself if you're overworked if that's a reflection of egotism you know because you might there

**9:40**

might be part of you that's thinking well you know only I can do this it's like there are probably some things that you're doing that only you can do but

**9:48**

you have to be able to maintain that sustain it across time but as I said even more

**9:53**

importantly the probability that you're the only person that can do absolutely everything you're doing is very low

**10:00**

there may be some things that you're particularly good at you should obviously be doing almost nothing but that so on the tours for example I don't

**10:07**

do anything but show up I show like there's a rule I'm to be there an hour before come hell or high water and ready

**10:15**

so I have to have a rest beforehand I don't pay attention to flights I don't pay attention to hotels I don't pay

**10:20**

attention to restaurants or any any details whatsoever I have people that I

**10:27**

follow when I'm walking through airports like all I'm doing is focusing on the tour and I suppose a subsidiary concern

**10:34**

there is my wife because she travels with me and we have to set up the tour so that she's also thrilled to be along

**10:42**

and thrilled matters because we've been trying to make this which is probably the most intense thing that I do we've

**10:48**

been trying to make this sustainable and to make it sustainable you have to not be upset

**10:53**

about it cuz otherwise you'll just you'll stop doing it and so well

**11:03**

well you handle more responsibility and Opportunity by building a more differentiated sub substructure under

**11:10**

you and that's the other thing that's cool about that is there's no limit to what you can do then right because you just keep building layers of

**11:17**

infrastructure beneath you and if you hire properly and you're very careful about that then you can just keep

**11:23**

jumping up the ladder so to speak that's how you're that's how you work neurologically by the way way when you

**11:30**

pay attention to something and you practice it you build little automated structures that are neurological and

**11:35**

then they run unconsciously and then your Consciousness jumps up a letter a level so that you can concentrate on

**11:41**

things that haven't yet been automatized so you're trying to put in routines all the time underneath you so that you can

**11:47**

free yourself up to attend to only those things that are crucial you know that if you study people too like Steve Jobs and

**11:54**

Elon Musk I mean jobs in particular was absolutely I know people who' worked with him very closely as well as musk

**12:02**

jobs was unbelievably good at deciding what he wasn't going to do right he put all his attention on the things where

**12:08**

the maximum return would be this is something to know too even technically so you know you've heard about the 8020

**12:14**

rule I presumes 20% of your customers provide 80% of your business that's not

**12:19**

the rule the rule is way more remarkable than that so here's the

**12:28**

rule among the people that work for you the square root of the number of people that you that work for you do half the

**12:36**

work so that means if you have 10 employees three of them do half the work but if you have 10,000 employees a

**12:43**

hundred of them do half the work now this is an unbelievably well

**12:48**

documented phenomenon I'm not telling you something that's in the realm of speculation this is a this is a solid

**12:53**

statistical law now there's a rule that goes along with it this and this is very

**12:58**

difficult for managerial people to understand because they almost always do exactly the opposite spend all your time

**13:04**

with your most productive people now the typical manager does exactly the opposite they find the 10% of their

**13:11**

staff that are floundering and spend all their time with them I can understand why you do that

**13:17**

from the perspective of let's say sympathy although it's counterproductive you're not going to help them you don't

**13:23**

have the ability you don't have the time they don't have the motivation it's not going to work you spend all it's not

**13:30**

going to work you can't do it you spend all your time with your most productive people and the same with your own use of

**13:36**

time is you spend all your time on those things that are that you are best suited to do and you have to be brutal about

**13:43**

that and there's nothing in that that's anything but good because you end up

**13:49**

doing the maximum amount of good that you can in the most sustainable way and you provide the largest possible number

**13:54**

of people with the greatest opportunity like there's nothing in that that's anything but good

**14:00**

and the people who are floundering you know I had a hard time in my lab when I was a

**14:06**

professor letting people go when I should have and I learned to do that

**14:12**

quite painfully I would say one of the things I realized and this is something to really get in your head too if you

**14:18**

can especially if you're a little more on the agreeable side you don't like hurting people's feelings enabling someone's failure is

**14:25**

not a moral accomplishment and so if you have someone who's either outright

**14:30**

failing or or Worse kind of drifting along so they're not you know performing

**14:36**

poorly enough to really come to your attention but they're really not all in it's like there's no reason not to sit

**14:43**

down with them and say like you know you're not thriving so what the hell are you doing

**14:50**

you want to drag your Sor carcus through this job doing a second you know hitting

**14:56**

this in the second rate manner for the next 15 years as you age painfully or do you want to go out and see if you can

**15:03**

find something you could commit yourself to like this is not a game and so

**15:08**

there's some pain in letting people go but there's pain in M There's real pain

**15:14**

in maintaining people in a quasi failure situation and so it's better just to say

**15:21**

why don't you go find something you want to do and you know people don't like change

**15:27**

and they might be all upset about the fact that that didn't work but you lying about the fact that it's working isn't

**15:33**

helping them and then you could put someone in that position who's like pretty thrilled

**15:39**

to be there and is they're going to devote themselves

**15:44**

completely to it and then you know God only knows how good that's going to be for them and the people around them the

**15:49**

other thing other problem with having people around or doing a second rate job is that they're really hard on the

**15:55**

people that work for them you know they don't know to distribute reward properly they're

**16:00**

jealous of anybody who's working effectively they're going to push down anyone that they see to be a threat

**16:07**

they're going to you know hoard information no you you just describe the

**16:12**

typical day of most entrepreneurs yeah hey the management side is a tough one

**16:18**

you know it's a tough one and it's hard to wrap your head around the balance

**16:23**

between separating the wheat from the chaff let's say and being sympathetic and kind but sympathetic and kind in the

**16:31**

moment is not a good medium to long-term strategy it's kind of the difference on a trait level it's the difference

**16:37**

between being agreeable agreeable people avoid conflict and you can understand that and

**16:44**

they default towards sympathy and and mercy let's say um conscientious people

**16:50**

look at performance and agreeableness isn't a bad ethic for within a family

**16:56**

but conscientiousness is the ethic that works on large scale Enterprises and conscientiousness is pretty

**17:01**

straightforward it's like can you do the job or not and if the answer is no well then

**17:07**

you should find a different job you know or retool your attitude that's unlikely

**17:13**

by the way and you know the probability that you as a manager is going to are

**17:18**

going to get someone to shift their attitude at a fundamental level it's pretty low like especially if they're

**17:24**

really in a failure pattern because you don't even know what the hell's going on with them and so better to pay pay

**17:31**

better to spend your time with your high performing people it's a very hard thing to learn and it's it's cruel in a way

**17:38**

you know it has that El element of Cruelty but not in the long run you know

**17:44**

I I have an idea though like so I've got you know you your first book was maps of meaning then you got 12 rules for life

**17:50**

and then beyond order but if you wanted to do a spoof book and do the complete opposite of everything he just said and

**17:55**

then have Beyond chaos I think it would yeah bad idea bad idea yeah well I

**18:01**

thought I've thought about writing a book on how to fail right no I think it would be pretty funny yeah well there's lots of ways yeah yeah yeah well what's

**18:09**

his name Robert Green he's kind of done that he's done that in some ways by laying out the P he's laid it laid out

**18:15**

in in his books he's laid out what would you say a description of psychopathy you

**18:20**

know and that's useful to know because there are psychopaths in the world and you need to know how to handle them

**18:25**

without becoming one right which is a difficult thing like contagious where you can become a

**18:34**

psychopath yes it's well it is contagious I mean one of the things we do know for example is that the worst

**18:40**

thing you can do with people who have an antisocial proclivity is to group them together so there's a famous study done

**18:46**

in 19 1930s in a in a town called Somerville in Massachusetts um was one

**18:53**

of the first large-scale epidemiological studies designed to remediate antisocial behavior and would be Behavior that's

**18:59**

associated with criminality and children who have a criminal bent their diagnosis

**19:05**

is childhood conduct disorder and so you can identify precursors to criminal behavior in children early sexual U

**19:13**

experience for example is a marker just so you know um they the Somerville crowd did an

**19:20**

intervention with with inner city kids in the 1930s designed to Sidetrack kids

**19:26**

who were at risk for later criminal Behavior so from broken families for example in lower socioeconomic in lower

**19:34**

socioeconomic neighborhood and they basically threw the works at them in terms of interventions and uh divided

**19:41**

them randomly into an intervention group and a non-intervention group was actually a well-designed study and uh

**19:48**

you know they taught them to read they taught them social skills they taught their parents parenting skills they did everything you could possibly imagine

**19:54**

that might help remediate this developmental

**20:00**

trajectory towards criminality one of the things they did was they took the kids out of the uh Urban environments

**20:06**

and put them in camps in summer camps for two weeks a year and the kids loved it and the counselors loved it and

**20:12**

everybody thought this the whole program was great and then they de blinded the study and analyzed the results and the

**20:18**

kids in the intervention group did far worse much more likely to be alcoholic much more likely to be criminal much

**20:24**

more likely to suffer from severe illnesses like schizophrenia and when they did the detailed an is they found

**20:29**

that the reason for that was that they grouped them together in summer camps and they learned to compete to be

**20:35**

criminal right and so one of the things we know this is one of the real failures of the prison system is there isn't

**20:40**

anything worse you can do for antisocial people than can to put them with other antisocial people because then they're

**20:46**

around antisocial experts and they compete right well it makes sense right

**20:52**

well that we also found too that uh so the Psychopaths not all criminals are psychopaths by the way it's a minority

**21:00**

of criminals who are psychopaths but if you put psychopaths in group therapy it makes them worse why well they get

**21:07**

better at doing what they do like they're already manipulators that's pretty much how they operate like if if

**21:13**

I'm a psychopath and I'm talking to you the only thing I'm concerned is is with

**21:19**

what you can deliver like that's it you're just a landscape of opportunity and if you

**21:25**

happen to be kind and sympathetic so much the better right so if you put

**21:30**

Psychopaths through group therapy they get more effective doesn't remediate the

**21:36**

psychopathy at all it's also very very difficult to change that very very difficult it's very very stable from

**21:43**

like age four onward gotcha so yes you can teach people to be more criminal and more Psychopathic and we do that quite

**21:49**

effectively in our society by the way we handle them wow so yeah it's bad so you

**21:54**

you've uh you've had Chris Voss who's sitting here uh front row on your uh on

**21:59**

your podcast before so I I yeah and I was just wondered if if you were to

**22:05**

categorize him as a narcissist sociopath or psychopath how how do you think he would rate well fortunately I don't have

**22:13**

to answer that question you know you know what you are

**22:18**

so good at debates and making your case and backing it up with you know not only

**22:25**

your own view but stats I mean you have this incredible ability ability to Resource you know so much um how does

**22:32**

one develop that skill uh I don't know if everyone can because you can to a

**22:38**

greater or lesser degree I mean um it's helpful to have the innate ability let's

**22:45**

say so one of the things people differ in for example is a trait called verbal fluency It's associated with

**22:51**

extraversion and sociability and positive Emotion by the way but verbal

**22:57**

fluency is the r at which you can think up words and there's massive variation

**23:02**

in that so for example if I had all of you you can test it very easily so imagine I had all you people write down

**23:09**

as many words as you could that begin with the letter s in 3 minutes okay some

**23:14**

of you would produce like 30 words and some of you would produce 150 like it's a huge variation and it's It's

**23:21**

associated with verbal intelligence which is in turn associated with General cognitive ability but there are other

**23:27**

elements of intelligence that aren't verbal so you can have lower verbal fluency and and be very good at spatial

**23:35**

intelligence for example or manipulating images but High verbal fluency is very

**23:40**

useful with with regards to a career as a debater or public speaker and I mean I

**23:46**

don't know if you know who Camille pelia is but she's off the charts and verbal fluency Ben Shapiro he's another like

**23:52**

machine gun speaker Russell Brand those are the people I've met in my life who are the most verbally fluent and that's

**23:58**

huge part of that's an innate skill in terms of developing your ability to speak I would say well there's a variety

**24:07**

of things that you can learn to do I don't debate to win I'm not

**24:13**

particularly interested in winning I stopped doing that when I was in my 20s when I learned that that was a

**24:18**

counterproductive strategy what I'm trying to do when I speak is to say what

**24:24**

I believe to be true and that's a long-term vict iory like the truth is a

**24:30**

long-term strategy right and it's the opposite of manipulation and so all I'm

**24:35**

trying to do is to formulate my words as clearly as I possibly can and some of that's an embodied sense like if you you

**24:42**

can learn to you can learn to do this it's really worth learning although it's very unsettling when you start you you

**24:50**

**want to feel out whether or not the words that you're saying are like firm**

**24:58**

imagine you're qu crossing a swampy plane and you can't see into the water

**25:03**

you know there's a trail and underneath the water 6 in or so there are well set

**25:10**

Foundation stones and you can sort of feel them out as you make your way that's how Moses went across the Red Sea

**25:16**

you know the Sea of chaos is you can tell when you're speaking if you pay attention what words you're saying make

**25:23**

you confident and that's a way of telling that there's firm ground under your feet and it's the opposite of being

**25:30**

self-conscious you know if you start speaking publicly and you become self-conscious it's because you've

**25:35**

become concerned with how people are responding to you well it's not about

**25:41**

you it's not about you it's about the validity of your words and if you're

**25:46**

focusing on what it is that you have to say and you find the firm words you'll

**25:52**

be a compelling public speaker and that's the case too even if you're not particularly verbally fluent because

**25:57**

people will be to tell that what you're doing is wrestling with the ideas at

**26:03**

hand and trying to find your way forward and everyone wants to see that that's a

**26:09**

that's a kind of Highwire performance and so and that that's way different than wanting victory like Victory

**26:17**

there's lots of different kinds of Victory you know there's the egotistical victory of the moment and there's the

**26:23**

setting the foundations for Success across the broadest possible SP of time

**26:28**

and place into the future and the truth is a way better long-term strategy like

**26:35**

you might pay for it in the present which is why people lie obviously but so you want to find the right words now so

**26:42**

you you can learn to do that you got to listen to yourself talk and you got to think well do I actually believe that or

**26:48**

am I trying to impress this person or am I trying to close the business deal you know is there am I manipulating the

**26:55**

situation so that I get what I want rather than merely trying to represent

**27:00**

the truth now you might say well why shouldn't you get what you want and the answer is well what the hell do you know

**27:06**

I mean how often have you been wrong about what you want lots I presume and

**27:12**

how often have you got something what that you wanted maybe by the by a route

**27:17**

that wasn't the straightest let's say and found out that that didn't you do you any good at all it's much better

**27:23**

just to say what you believe to be the case and that also helps you build a foundation for speaking into the future

**27:31**

it also allows you to draw on your own experience you know like there isn't anyone who

**27:37**

can't comport themselves in a manner that's interesting one of the things I learned as a clinician was that and I

**27:44**

had a very wide variety of clients ranging from people who were just barely clinging to the edge of the Earth by

**27:50**

their fingernails to people who were extremely accomplished on multiple

**27:56**

Dimensions you know and even the simpler people even the cognitively impaired

**28:01**

people that I dealt with who ver who had in some cases virtually nothing going for them if I could listen hard enough

**28:09**

and get them to talk about what they knew they were immediately compelling and interesting and they had things to

**28:15**

say and I had things to learn from them and so you can be a compelling public

**28:20**

speaker if you actually talk about the things that you know to be true right

**28:26**

but that means you have to forgo the the ego games that are associated it's the same in a in a debate you

**28:34**

know it's a victory if you clarify your thoughts in the course of a discussion

**28:40**

that's a victory that's sort of independent of the perceived victory of the moment

**28:47**

let's say right yeah now the other thing you can do on the public speaking side is you watch watch your speech and you

**28:55**

should eliminate ums and likes and all those filler words that people use that

**29:03**

has to go it it makes you inarticulate and you can learn to control that and instead of filling the pause with an um

**29:10**

or a like or a you know you can just be silent like there's nothing wrong with

**29:16**

taking a pause and collecting your thoughts and you want to have your goal in mind like when I go on stage when I'm

**29:23**

doing my lectures when I'm touring I always have a question in mind mind right and that's a priority it's

**29:30**

like okay what am I talking about tonight here's the question and what does the talk consist of it talk it

**29:36**

consists of an attempt to not only answer that question but to push the

**29:42**

answer to the question farther than I've been able to push it before and that

**29:47**

adds some novelty to it and then the the talk becomes an exploration with the audience and that's way more interesting

**29:54**

for everyone you know you the last thing you want to do is is like read if you

**29:59**

can avoid that don't do that don't do that no matter how good your re your

**30:05**

presentation is you're going to lose most of the audience if you read it best

**30:10**

to have if you're going to use PowerPoint use images or just a couple of phrases and you can read the phrase

**30:16**

and then discuss it you know but people want to see you actively engaging in the ideas they don't want to hear some

**30:22**

canned and stereotyped set of responses and you're not there to plead the

**30:28**

audience you know they there to figure out something with everyone and what else can you do when you're in front of

**30:34**

a crowd you're going to be afraid of the crowd but you shouldn't be talking to the crowd there's no crowd you can talk

**30:42**

to an individual everyone so what you do and you pick out people in the group and you talk to them you know and you look

**30:48**

at them and when you walk on stage you look everywhere so that you're not afraid of what's in front of you and

**30:54**

then you just talk and you always pick people out and look at them and see if

**30:59**

they're paying attention and if they're not well you got to play with the audience

**31:04**

you know and so what is it get rid of the filler words get rid of the idea that you're there to accomplish your

**31:11**

goal your narrow goal try to say what's true see if you can find your way find

**31:17**

the words that make you feel solid it's the opposite of self-consciousness play a bit explore

**31:24**

have a question firmly in mind you know and risks some failure too that's that's

**31:29**

fun you go out on stage like I never know when I go on stage for a talk I never know if it's going to work and

**31:36**

neither does the audience and so they're all part of what grips them is the fact that I could just miss the mark you know

**31:44**

that it could go nowhere and that's a real challenge to see if you can put

**31:50**

together new ideas on the Fly and address the issue at hand and to bring everyone along for the ride and that's

**31:58**

there's no failure if you do that even if it doesn't work out that well like at least it's a noble attempt that went

**32:03**

somewhat sideways that's something and then people get to know who you are too and so do you and that's a good

**32:11**

deal can be a good deal so well so to that that point to get to know who you

**32:16**

are so you have put yourself many times in positions having discussions or

**32:22**

debates or interviews with people that you know dislike you you know they're going to try to challenge you uh are you

**32:31**

doing that uh I'd love to have you break down to to reach people that you feel

**32:38**

need to be educated on a different way of thinking about it are you doing it to

**32:43**

help yourself get better at thinking through these difficult sort of challenges I don't I don't set

**32:51**

out precisely to put myself in situations like that it's more like they

**32:57**

arrive you know I've done a lot of interviews and some of them have been with people

**33:04**

who are genuine interlocutors and others are

**33:10**

people who want to play a game and so I give people the benefit of

**33:16**

the doubt so if I meet someone I assume that we're playing a straight game and then I watch them and if they're playing

**33:24**

a straight game then then I treat them politely and if

**33:32**

they're not playing a straight game I think okay what the hell are you up to and the

**33:39**

problem is for them generally is I was a clinician for a long time and tricky

**33:45**

journalists think they're tricky and they're nowhere near as tricky as the people that I've dealt with they're not

**33:51**

even in the same universe and so I'm serious and so if I think okay you're

**33:57**

not playing a straight game I see so now we're playing clinician are we and so

**34:03**

then I can usually figure out what the person's up to and that's usually not very good for them so and I don't like

**34:10**

doing that you know like when I meet someone socially I'm not bringing my clinical eye to bear

**34:18**

it's the polite thing to do and the appropriate thing to do socially is to assume Goodwill and meet people there

**34:25**

and if you're not naive that that's a form of courage you know cuz I could be very skeptical when I meet people but

**34:32**

I'm not I think probably you're playing a straight game at at least mostly or and good then we'll go we'll proceed on

**34:39**

that basis but if that's not the situation then I'm also prepared to play

**34:46**

that game and so that's worked spectacularly well upon occasion yeah

**34:53**

and it was it was often with journalists who they weren't there to play a straight game at all and they were one

**34:59**

of them confessed in fact a woman named Nelly bus who she got me probably more

**35:04**

than anyone else did because she was she was very very devious very very devious

**35:10**

and she fooled me into thinking she was someone other than who she was and she

**35:16**

admitted several years later that her role at the New York Times was to seduce

**35:21**

essentially the people that she was interviewing and then continued to talk to them until

**35:28**

they said something that she could twist into reputation destruction and Elevate

**35:34**

her status in consequence she said lots of the New York Times reporters are playing that game and that's

**35:42**

a that's a pretty uh that's a psychopathic game and she

**35:48**

was particularly good at it now she did admit it and apologize

**35:54**

but those things aren't easy to change once you practice system and so you know maybe she learned her lesson and maybe

**36:00**

she didn't so so I don't look for trouble you know

**36:06**

um well I don't I don't look for trouble and I've avoided universities mostly

**36:12**

since about 2018 because they just got way too annoying I don't know why anybody ever goes and speaks a

**36:18**

university they're a pain in the neck they don't pay anything they're they

**36:23**

think that it's a privilege for you to speak there and sometimes it is you know that there is occasions where that's the

**36:29**

case but mostly it's just it's just not worth the trouble yeah and so I don't I

**36:36**

do that rarely you know and still now and then but rarely um in terms of

**36:41**

interviews mostly what we've changed as a family is I I won't do an interview without recording it and so often now if

**36:49**

I run into someone who's playing games we just release the whole recording and that usually does the

**36:55**

trick because I you know I I I'm not concerned about revealing what

**37:04**

it is that I've said and like you you may know that the Ontario College of psychologists and behavior an

**37:11**

analysts um they changed their name how convenient for them um they're trying to

**37:17**

take away my license you know and right now we're negotiating because I'm supposed to be re-educated which you

**37:24**

know isn't really going to work that well and

**37:29**

you know I told them that I would do their re-education but there's no bloody way they're going to be able to do it in

**37:34**

secret and they told me two weeks ago that they would proceed with the

**37:40**

re-education because they found someone who apparently is willing to do this but they told me that I couldn't record it

**37:47**

that they'd have a court recorder there to make a transcript but that I couldn't have the transcript if I didn't agree to

**37:53**

keep it secret and now the reason that those processes procedures are usually

**37:58**

secret is to protect the person who's being disciplined let's say not the people who are doing the discipline and

**38:05**

so I said well no I'm not doing that I'm going to make every bloody second of this 100% public clearly obviously

**38:15**

you're not doing this behind closed doors so well that was the last letter we sent back to them I don't know what

**38:21**

the hell they're going to do about that but but there's there isn't a hope in hell that they're going to be able to

**38:26**

stop me from recording this like not unless they're willing to do a cavity

**38:32**

search so seriously like this is not happening in secret I've got would I say

**38:38**

I have nothing to hide you know everyone has something to hide let's make no you

**38:44**

know mistakes about that but there's certainly nothing that I could possibly say in the course of a

**38:50**

re-education episode whatever the hell that would be that I wouldn't be 100% willing to make public and that's also

**38:56**

part and parcel of of this the consequence of this finding my words carefully you know it's like I'm not

**39:03**

saying things I don't mean and then you might say well what do you mean that you mean something it's

**39:10**

like if I say something if I say no for example and I've said no I've said no to

**39:17**

government legislation in Canada what no means is there isn't anything you can do

**39:23**

to me that would force me to comply with your request T and I've thought it

**39:30**

through and so I did a lot of negotiating counseling with my clients

**39:35**

you know I I know what no means I know how rarely you use it you use it when you mean it and to mean it means you

**39:42**

have to think it through and if if you want to stop someone from having the upper hand over

**39:50**

you you just have to give up everything they want you have to think that through it's like okay you're going to take my

**39:56**

license can I live with that well then I have to have a plan if that happens what

**40:01**

am I going to do you know if I'm all panicked about that well then I lose but

**40:06**

if I've Got a Way Forward it's like okay do your worst and so well then what you know if

**40:13**

you take away the upper hand you're free and all you have to do to take away the

**40:19**

upper hand is to give up what's being requested and now that you may have to think that through

**40:25**

but they might take it anyways even if you don't think it through so you might as well think it through and you know

**40:32**

you may also find that unbeknownst to you there's tremendous opportunity in

**40:37**

that sacrifice you know like with the college for example with the psychologist it's like not obvious to me that I want to be

**40:44**

part of their damn Club anymore because they become unbelievably corrupt like the medical establishments the medical

**40:51**

associations you know I'm not going to let them take my license because I'm not going to let a pack of faceless bureaucrats take something me without

**40:58**

making their life hell but that doesn't mean that I'm happy to be part of their

**41:03**

little codery so but I've already I can live without my license I've got lots of I'm

**41:11**

not out of options not by any stretch of the imagination so yeah that's for sure

**41:19**

uh so you did this I thought fascinating video where you analyzed Elon Musk tulsy

**41:26**

Gabbert and uh JD Vance and uh Bobby Kennedy and Trump right and so in so I

**41:34**

had a zoom with you uh the day before the elections and Trump has won uh and

**41:40**

now we have all these people that are losing their minds that have Trump

**41:46**

derangement syndrome but there's people that have Jordan Peterson derangement syndrome or Bobby Kennedy derangement

**41:51**

syndrome or tucko Carlson derangement syndrome uh what do you first first off love to

**41:57**

get your thoughts on where we're at now you and you can't vote CU you're a Canadian so but you have a tremendous

**42:03**

amount of insight on politics and you're you're doing stuff well I could talk about the Democrats you know I worked

**42:10**

with the Democrats behind the scenes for like six years a long time and and quite a lot um

**42:20**

a friend of mine who I worked with who was very well connected with the DNC and

**42:27**

the Democrat hierarchy nationally he's one of their main political strategists

**42:33**

he just so you all know this is something perhaps you would like to know in

**42:39**

2017 I made an offer to the

**42:45**

Democratic party Elite me and Rogan and Dave Rubin and Brett Weinstein and Ben

**42:52**

Shapiro we invited them all to come on our podcast it was an open Ed offer we

**42:57**

have it in writing my friend his name is Greg herwitz released this the other day on Twitter because all the Democrats and

**43:04**

the Legacy Media types are squawking up and down about the fact that the conservatives have you know created this

**43:10**

New non-legacy Media space and are dominating it and how unfair that is it's like you sons of we asked

**43:17**

you for seven years 7 years to come and

**43:22**

talk to us and he Greg got nowhere he couldn't find one now I eventually

**43:27**

talked to Dean Phillips who had run for president on the Democrat side if you may remember Dean because he dropped out

**43:34**

fairly early in the presidential race and he was willing to talk to me because he just got Savaged by the Democrat

**43:41**

Party structure when he dared to put his foot forward as a genuine Contender on the Democrat side so I did get to speak

**43:48**

to the odd Democrat who got bitten so hard by the radical leftists that they

**43:53**

well that they were that they were willing to share their experience let's say um why am I bringing that up well

**44:02**

one of the things that we're going to have to wrestle with going forward is you know the country is very disunited

**44:08**

and it isn't useful that half the population let's say the rough half that

**44:13**

voted for camela Harris are living in Terror of the Trump mob first of all

**44:18**

because I don't think that's necessary and second Trump's going to have to work with those people in many ways anyways

**44:25**

and generating a bunch of of additional enmity isn't going to be helpful like the Democrats are going to have to wake

**44:31**

up to the danger of the radical leftists and they're so asleep on that front that it's a kind of bloody Miracle you know

**44:38**

even when I interviewed Mr Kennedy first that was a year ago when he just was starting his

**44:45**

presidential campaign I asked him a question that I've asked all the Democrats that I've had private

**44:50**

conversations with because these people will speak with me privately but not on the podcast I said when does the left go

**44:57**

too far none of them by the way I never got an answer from any of the Centrist

**45:02**

Democrats to that question which is really quite appalling and Kennedy said I don't want to run

**45:09**

that kind of divisive campaign and I thought well you know fair enough but that's not a very good answer because

**45:15**

there's real problems on the radical side of the Democrat political Spectrum as there are there are commensurate

**45:22**

problems although they're not as profound yet on the right-wing side

**45:27**

because there's no shortage of derisive Anonymous gleeful

**45:33**

right-wing anti-semitic trolls online and there's plenty of them and they're noisy as hell and they're not good but

**45:40**

they don't have the institutional power that the progressives have especially in the universities they're just completely

**45:46**

blind to the danger of the Progressive Movement and they won't we've been talking to the

**45:52**

Democrats for seven years like the message was very clear the radical are

**45:57**

going to do you in and their answer was they don't mean what they say it's like

**46:02**

have it your way they mean it when camela Harris was Camala Harris was talking about Equity she either didn't

**46:10**

know what she was talking about which is inexcusable or she knew what she was talking about which was malevolent those

**46:17**

are the options it's like they just mean equality of opportunity it's like then why do they have a different word they

**46:25**

don't mean equality of opportunity they mean equality of outcome

**46:30**

and if you're foolish enough to believe in equality of outcome then you deserve to lose the Senate lose the house and

**46:37**

lose the presidency

**46:42**

right and that's what happened yeah you know and I think I was talking

**46:49**

to herwitz today and he said that he believed that the swing issue was the

**46:54**

trans issue that was enough to swing the vote and rightly so because what's

**47:00**

happening with regards to this surgical sterilization and mutilation of children is I have never seen any worse form of

**47:09**

medical and psychological malpractice in not only in my life as an observer of

**47:14**

the psychological and medical community but in my studies of serious

**47:20**

Psychopathology it is brutal and unacceptable beyond belief and it's part

**47:26**

of the ID ology that the Democrats wouldn't the moderate Democrats would not recognize and

**47:32**

so they've got a fair bit of mopping up to do and I hope they manage it because it would be good for a trump

**47:39**

Administration especially one that's got the reins of power the way that Trump now does to have an effective opposition

**47:46**

you always need an effective opposition now you need an effective opposition within the confines of your own family

**47:52**

you know so hopefully they'll

**47:58**

do a little soul searching and decide that postmodern communism is not the

**48:05**

right way forward so we'll

**48:12**

see what what what advice would you give to someone that is in their mind they

**48:18**

believe Trump is a rapist Trump is a racist Trump is this horrible human he

**48:23**

doesn't care about people and he's also the president of the well the first thing you could probably do is stop

**48:29**

watching CNN and MSNBC it's like seriously you know I've been watching in

**48:34**

the last week it's been unbelievably interesting from my perspective personal perspective even to watch the Legacy

**48:40**

Media finally wake up and realize that it's not 2005 you know 6 months ago 7

**48:47**

months ago I read a an account of Gavin Nome opining about Joe Rogan and me he

**48:53**

said that his own son was watching Rogan and me and other Fringe figures and I

**48:59**

thought I don't know what planet you occupy Mr Nome but Joe Rogan is the most powerful journalist who's ever lived by

**49:06**

an order of magnitude you know CNN is The Fringe MSNBC is The Fringe Gavin

**49:12**

Newsome is The Fringe Joe Rogan is he runs the most popular podcast in 92

**49:19**

countries it's like that's not Fringe and so

**49:27**

if you are suffering from Trump derangement syndrome I would say you could watch the podcast he did

**49:34**

with Rogan and with Theo vaugh and you could see what he was actually like when he wasn't completely on the defensive

**49:42**

from being attacked like no other politician in living memory has ever been attacked and the but more

**49:49**

importantly than that even independently of trump himself and I actually think that all the torture that he's gone

**49:55**

through in the last 8 years years has mellowed them out to some genuine degree even if you're frightened of trump it's

**50:02**

like oh so you're also frightened of Kennedy who was a Democrat and you're frightened of Tulsi gabard who was a

**50:08**

Democrat and you're frightened of VI ramaswami and um Vance who in a normal

**50:15**

world would be a Democrat and Trump himself who's pretty weird Republican it's like it's not like well seriously

**50:23**

Trump as a republican what a crazy world we live and so Trump has gathered these

**50:29**

people around him and he's invited them in and accepted them and they're a very strange crew and even if Trump has his

**50:36**

rough edges which he genuinely does it's like well he's not alone there now and so that's a really good deal like my

**50:43**

sense was especially when musk jumped aboard I thought oh if musk would do

**50:49**

something like establish a a department of governmental efficiency I would support Trump just

**50:55**

for that like just just that but that's not all he's got I think Gabbert is great she's very very solid she's the

**51:02**

candidate the Democrats should have run She's Everything CA Harris claimed to be it's like why the hell didn't they run

**51:07**

her they could have you know maybe it's because she had her own thoughts I mean

**51:13**

who knows well

**51:19**

sir so you know well and then the other thing I'd say about Trump and this is even more important than the team which

**51:25**

is really relevant but more importantly the best predictor of someone's future behavior is their past Behavior so if

**51:32**

you're hiring someone you should look at their General cognitive ability you should look at their temperament but if

**51:38**

you have a track record that's quantifiable of their performance in

**51:44**

that position and it's positive it's like there you go that's the best evidence that you

**51:50**

have technically and I don't know if everyone forgot but Trump was President

**51:55**

for four years and he wasn't Hitler in

**52:01**

fact zero Wars zero Wars is not many

**52:06**

wars right and more than that more than that zero Wars that's not nothing that's

**52:13**

remarkable accomplishment you know and but more than that he also spearheaded

**52:18**

the Abraham Accords now the possibility of establishing the Abraham Accords was

**52:23**

there in the previous Democrat administ ation and they the state department

**52:29**

defined it as impossible and they had for decades and even in the Trump Administration it took the Trump people

**52:35**

a couple of years before they were willing to take the risk but they did take the risk and you know you may have

**52:41**

noticed or you may not of is even after October 7th even after Iran did

**52:47**

absolutely everything it could to drive the Muslim world into the hands of the

**52:52**

extremists they they pulled no punches in doing that it was a last ditch attempt to save their sad mullah

**53:00**

hides they Abraham Accords held and I know that if Biden would have been this

**53:07**

is an appalling fact if Biden would have been willing to give Trump some credit which he should have because Mr Trump

**53:13**

might have just ridden off into the sunset If he if they had been willing to give the devil is due you know he should

**53:20**

have got the Nobel Peace Prize for those abrahamic cors but even more importantly the Saudis were ready to sign that damn

**53:27**

Accord and Biden wouldn't do it because it would shed positive light on Trump

**53:32**

and that was inexcusable it was inexcusable and my suspicions are that

**53:37**

you know if things lay themselves out like we hope they might that the Saudis will sign the Abraham Accord in the next

**53:43**

year or so and that's a big deal you know it it it might even stop

**53:49**

the you know there's terrible animosity developing in many ways

**53:55**

between the extremists in the Islamic world and the West broadly speaking if

**54:00**

you're paying attention to X you saw what happened in Amsterdam this week which was just absolutely unforgivable

**54:07**

and almost completely underreported on the Legacy Media you know but there are

**54:13**

positive things Brewing within the Islamic world and it's possible that the abrahamic Accords are a pathway in that

**54:19**

direction and so and Trump he established those so no Wars and the

**54:24**

Abraham Accords and four years without being Hitler it's like what the hell are you worried about he's going to be

**54:30**

Hitler now why now like what's changed why would he be he's not going to run

**54:36**

again not least cuz he can't but he's also how old is he he's 78 he's like

**54:42**

four more years I know he's a tough bastard and he can keep well he is and he's got a tremendous amount of energy

**54:49**

but you know he's got all these other people around him now my sense is he'll be able to

**54:54**

just finish out these four years and end it with Grace and I

**55:02**

I given that he was President already for four years in his track record it's like what are you worried about you

**55:08**

think that was all a ruse and the thing about Trump is he didn't know what he was doing that the

**55:14**

first time around you know he didn't know who to hire he didn't he did he wasn't a politician he didn't know anything about the ins and outs of

**55:20**

Washington really well he's a whole different character now and you know his team is already started the difficult

**55:27**

process of hiring the you know tens 10,000 people that they have to staff

**55:32**

the new Administration with they're already all over that and so I think I think and pray that he'll be much more

**55:40**

successful the second time and hopefully he can be magnanimous you know and say to the Democrats who've been terrified

**55:47**

into paralysis by the lies of the Legacy Media it's like you know you guys can

**55:53**

just relax we're not going on a Witch Hunt we're just gonna get the economy rolling better than it

**55:59**

ever has in history and we've got the people behind us to do this we've got important things to do and so you know

**56:05**

sit back and watch and try not to fret too hard and you know the probability that the world's coming to an end is

**56:12**

actually much lower than it was a week ago you know well you've already seen that you know you've already seen Hamas

**56:20**

make peace noises and you've seen the same thing with China and Russia that's not too bad for like three days and so

**56:27**

it wouldn't surprise me it wouldn't surprise me at all if Trump had a peace agreement in in hand with Russia and

**56:34**

Ukraine before he takes office and I know I don't know if you know this but there were peace offerings on the table

**56:40**

in May of 2022 and they were solid and the Russians were ready to sign and the Biden Administration refused it now you

**56:48**

know I think there's room for wide relevant differences of opinion about

**56:54**

the situation in Ukraine and Russia but it is not like it's not like the Russians won't deal especially if

**57:01**

they're dealing with Trump and so I guess I'd ask the Democrats who are

**57:06**

reasonable it's like well hold your nose for 6 months you know and try not to freak out and another thing to think

**57:13**

about too and this is good in a general political sense I've thought about this very deeply you know in the biblical

**57:19**

story of Exodus Moses is the archetypal leader and he leads his people away from

**57:26**

slavery and tyranny toward the promised land which is always what a leader does by the way through the desert of Doubt

**57:32**

toward the promised land and Moses is severely punished at the end of his life

**57:38**

for using Force when he's called upon to use persuasion right so at near when the

**57:45**

Israelites are are on the border of the promised land they run out of water it's

**57:51**

physical water and the Water of Life and God tells Moses to to to speak to the

**57:57**

rocks and have them deliver the water that will redeem the Israelites and instead Moses takes his staff of

**58:04**

authority that Rod you know that can turn into a serpent that's the magical symbol of healing by the way that the

**58:10**

Physicians use he takes that rod and he he strikes the Rocks twice to force them

**58:16**

to comply and God's response to that is that he sentences Moses to death before

**58:21**

he reaches the promised land and that's a hell of a punishment for someone who who had been a what would you say a

**58:30**

devoted a devoted servant of God for decades and who undertook an unbelievably responsible task and who

**58:38**

United the fractious Israelites and took them away from slavery he's punished why

**58:44**

because he used Force when he was asked to invite and convince and so one of the

**58:51**

things to consider too when you're trying to evaluate the claims of any given political leader any leader or

**58:57**

yourself for that matter is if you use fear and compulsion then you're a tyrant in

**59:04**

Waiting you should formulate your offerings to people in the form of an invitation it's like here's something we

**59:11**

could do together you know are you on board now it's a little bit more difficult in the case of those people

**59:18**

who just will not fly right you know like what do you do with criminals invitations don't work very well and so

**59:24**

you know you still have to have a cynical eye for people who misbehave

**59:29**

let's say but by and large you should be structuring your policies on an Invitational basis that's also how you

**59:36**

Foster trust that was the big catastrophe with the covid debacle it's like we're going to use Force it's like

**59:43**

okay we're not going to trust public health for the next five decades how's that for a response well that's a bit

**59:50**

counterproductive All Things Considered you know that's a good thing to think about when you're negotiating too it's

**59:55**

like you want people fully on board with your offer because then they bring their best to the table and you don't do that

**1:00:02**

with fear and you don't do that with compulsion and so when you're watching the climate Nazis for example brandish

**1:00:08**

their flags of Terror you think well you're trying to frighten me into commiss into

**1:00:13**

submission maybe I don't trust you then if your tools are fear and force we're doing this for because it's

**1:00:21**

better for you it's because it's going to bring a better future into being I see so you're going to use fear and

**1:00:27**

force to bring a better future into being I don't think so I don't think so and so that's part

**1:00:34**

of what makes me skeptical of the climate well there's 50 things that make me skeptical about it but one of them

**1:00:41**

the most fundamental is likely I see you're going to compel people to do this are you instead of making energy cheaper

**1:00:49**

which is what you would do if you were competent no we're going to make it five times as expensive and we're going to force you to use it it's like okay got

**1:00:56**

it I understand they've done that in the UK right UK Energy prices are about five

**1:01:01**

times what they are in the US and that means all the poor people are way poorer

**1:01:06**

than they would have to be and I don't see that as a net gain so yeah I want to

**1:01:13**

do a shout out we have a mutual friend Alex Epstein who wrote the book fossil Futures and his first book was a moral

**1:01:19**

case for fossil fuels he has a great website energy

**1:01:26**

the research and the data and the language so that they can speak effectively about energy and he's just I

**1:01:31**

think he's absolutely brilliant has put so yeah yeah yeah yeah he's a single-minded terror

**1:01:36**

Epstein yeah yeah he's very useful to totally well let let you know what when we were talking um uh you know I have a

**1:01:45**

book life gives to the giver which is this is a really clever way of me plugging my book while I'm interviewing you um but we were talking about giving

**1:01:52**

and you had made this comment which I loved because me and Dan Sullivan did a whole podcast on this where you said the

**1:01:58**

the term and I didn't initiate this you said it you're like this whole uh this

**1:02:03**

term uh give back it's just it's just not I think you maybe use toxic I'm not sure how you described it but I'm

**1:02:10**

finally going to give back I've been robbing you people blind while I made my fortune and finally I'm going to give

**1:02:16**

back it's like that's a great message for capitalists and entrepreneurs it's like you're completely right that I was

**1:02:21**

a thief but now I'm guilty and so it's like one of the the things I've been talking to entrepreneurs about

**1:02:28**

especially on the energy side it's like you you got to give up your guilt it's it's pathological like maybe you have

**1:02:35**

some things to be guilty about you should sort that out but with regards to your well seriously but with regards to

**1:02:41**

your fundamental Enterprise it's like you you you built a thriving business well what are you getting are guilty

**1:02:47**

about that you think you if you stole from people while you're doing it well then you need a slap and you should straighten yourself out but if you

**1:02:53**

actually built an Enterprise that works and that you're off offering people a valid service and they're accepting it

**1:02:59**

voluntarily and you're efficient enough to do that profitably and you employ a bunch of people and you're growing it's

**1:03:04**

like that's good you that might be good enough you don't have to give back you

**1:03:10**

know all that means is you've accepted all that leftist propaganda that property is theft or some bloody thing

**1:03:16**

property is theft except their property you know and so no no it's it's time for

**1:03:23**

especially conservative entrepreneurs or just bu of ver in general to drop that idiot guilt I mean one of the I've been

**1:03:29**

in a lot of countries like a lot and and mostly in the west but one of the things

**1:03:34**

I can tell you for certain there is something about this country that's different from every other country and

**1:03:42**

what's different about this country is that the there is a default admiration

**1:03:48**

in the United States for Success the default assumption in the United States is you can succeed and you can deserve

**1:03:55**

it and then there's another assumption that's sort of right underneath that which is my children could be one of

**1:04:01**

those people who succeeds and deserves it now everywhere else in the world including my home country there's this

**1:04:07**

ambivalence about success it's like it's uh well you know are you sure you're not

**1:04:13**

part of the power mad patriarchy and just taking from people and you know that's a question for your own

**1:04:18**

conscience if you're a crooked dealer and some of what you've acred is a consequence of you know sharp trading

**1:04:23**

and lies well you know that's on your own conscience and you bloody well will pay for it but if you've played a

**1:04:30**

straight game and generally the only way to make a business that succeeds across any reasonable span of time is to play a

**1:04:35**

straight game then you should stop being guilty about it you should be the

**1:04:41**

opposite of that I think it's that this is what an Rand got right it's like there's an element to

**1:04:47**

entrepreneurial Kingdom building that's as laudable as anything you could manage it's not an easy thing to run an

**1:04:53**

efficient organization that offers people at genuine service at a competitive cost that they can use

**1:05:00**

voluntarily and that they're happy with that's a moral

**1:05:07**

accomplishment yeah in your country it is definitely the case you know I mean I've gone through almost all of Europe

**1:05:14**

and and and met many people in all of those countries and I know Canada and the UK extremely well and Australia New

**1:05:21**

Zealand no you guys there's something unique about the United States and that that's that American Dream element that

**1:05:29**

that admiration for entrepreneurial Excellence that while you see that manifested in someone like Elon Musk and

**1:05:36**

you know two thumbs up for that as far as I'm concerned and it would be lovely especially over the next four years if

**1:05:43**

all you entrepreneurial types stop letting the radical progressives have the moral upper hand because they're for

**1:05:48**

the poor it's like no they're not not a not even a bit all the bloody green

**1:05:54**

leftists have done in Europe is doomed the poor to extensive and deteriorating poverty that's all they've done they

**1:06:00**

haven't cleaned up the environment one bit electricity is five times as expensive in Germany as it is in France

**1:06:07**

and they burn more coal than they did before they shot off their nuclear power plants so not only is energy expensive

**1:06:15**

and unreliable and provided by dictators it's much filthier than it was they

**1:06:21**

failed on every single front all the while raising ra you know flying the flag we're for the poor it's like I

**1:06:27**

don't think so if you're making energy more expensive you hate the poor it's

**1:06:32**

straightforward you make people Rich by making energy cheap and so hopefully the Trump Administration will act on that as

**1:06:40**

he did before and drive energy costs down so America can like bullet forward like this

**1:06:47**

country is capable of and establish an example for the world like you have so many times so that would be a lovely

**1:06:54**

thing to see and you know if you're figuring out how to provide better services for lower cost which is what

**1:07:00**

all of you are doing at least to some degree in so far as your Enterprises are successful you are in service of the

**1:07:07**

poor and we know perfectly well we know with 100% certainty that free markets

**1:07:15**

and voluntary trade is the pathway out of poverty for the world there is no doubt about that and anybody who claims

**1:07:21**

different is ideologically addled narcissistic and what would you say and

**1:07:27**

morally posturing and so it's time for you entrepreneurial types to drop your

**1:07:32**

guilt with regards to your success that I mean assuming that like I said you know you may have bits of your

**1:07:38**

conscience to come to terms with but so does everybody else and you can fail dismally and be an immoral rat too you

**1:07:46**

know so the mere fact that you haven't accomplished anything doesn't indicate that you're

**1:07:51**

virtuous so \[Applause\]

**1:07:59**

so it's really hard to get you excited about certain subjects I mean that's that's uh let me do some rapid fire

**1:08:06**

questions then I'd love to take just a few minutes for some uh just a maybe a

**1:08:11**

couple questions from the audience so two to four tops just because of timing

**1:08:16**

uh so favorite book Crime and Punishment uh solution to suffering

**1:08:27**

responsibility most difficult time in your life oh there is a period of about 3

**1:08:34**

years not very long ago where my wife and my daughter and I were both extremely ill and so that lasted about 3

**1:08:40**

years and so that was three is a lot one is a lot three is a lot so and that was

**1:08:48**

really brutal okay uh favorite place to travel Florence Italy is hard to beat

**1:08:57**

um I went to this place called meteor in Greece too and man that was something else that's a strange place that used to

**1:09:04**

be an underwater ocean and it's all it is is this landscape of mesas they're

**1:09:09**

really tall like 1500 ft and in this Stark mountainous landscape and it

**1:09:15**

there's 24 monasteries there built on these absolutely inaccessible Cliffs it's it's well they filmed a James Bond

**1:09:24**

movie there for a reason it's like it's like shangra La Meteora deadly

**1:09:29**

remarkable place I'm I'm glad I'm getting my travel plans here too this is helpful um entrepreneur you

**1:09:37**

admire well Elon Musk is definitely one of them I have a brother-in-law Jim Keller and uh he's a he's an absolute

**1:09:45**

genius Jim he he's worked for Elon he worked for Steve Jobs Jim designed all the computer chips and everything that

**1:09:51**

you use all the apple chips virtually all the AMD chips all Intel chips Jim is

**1:09:56**

the chip designer who moves from company to company competing with the last chip that he built and he's built he's

**1:10:03**

building a printer at the moment that he thinks he'll be able to print anything and so like a 3D printer yeah wow yeah

**1:10:13**

yeah Atomic level deposition so we're going to see things come up in the next 10 years that we just can't possibly

**1:10:20**

imagine and musk is definitely on the Forefront of that you know that those cars he's build those self-driving cars

**1:10:27**

those aren't cars those are robots they just happen to have four wheels and musk is going to

**1:10:34**

take all the data that those robots have already collected which is a lot and he's going to put all that data into his

**1:10:40**

Optimus robots and that's coming down the pipelines unbelievably quickly so

**1:10:45**

assuming that we don't allow everything to go to hell in a hand basket which we certainly

**1:10:51**

could we're going to see things in the next 10 years that no one's going to be able to believe

**1:10:56**

so and musk is definitely going to be at the Forefront of that he's quite

**1:11:01**

the improbable creature and now you've got him in your government assuming that

**1:11:07**

everybody allows him to live I guess we'll find out about that but I got to find that Meme that I uh you know if

**1:11:15**

some uh someone on my team could text me the meme I showed yesterday morning about Elon Musk now he you know it it it

**1:11:21**

was um uh said along the lines of uh how stupid him to spend 44 million on

**1:11:27**

Twitter now he just controls three branches of government yeah no kidding yeah yeah you don't second guessing Elon

**1:11:34**

Musk is a Fool's game he doesn't know what he's doing it's like how many Rockets have you sent to Mars well

**1:11:42**

seriously you know people are so presumptuous you know if he'd only done one impossible thing you'd think you

**1:11:47**

could you know you could excuse that because you're so embarrassed to not be him and you could excuse that and say

**1:11:53**

well it's government subsidies or it was handed to him which is all complete bloody rubbish cuz you can hand

**1:11:58**

government subsidies to a fool forever and all that'll happen is you'll get 1,600 ft of High-Speed Rail built in

**1:12:05**

California in 20 years for \$1 billion you know and so that happened right that

**1:12:11**

happened and so but musk has done like five impossible things and so five is a

**1:12:17**

lot like one is a lot but five that's just that's really a lot and so second

**1:12:22**

guessing him it's like why did he spend 40 billion dollar on Twitter it's like cuz he knows things you don't like many

**1:12:30**

things books full of things so that's great yeah he's he's an incredible entrepreneur yeah and I think he's a

**1:12:36**

good person or I said in my analysis or he's an absolutely terrible person trying really hard to be good which is

**1:12:43**

that's even better and closer to the truth and I think it is the truth in his case cuz he's a complicated guy he's got

**1:12:49**

some dark corners but you know he's doing his best to aim up as you can tell by the fact that he's shooting Rock to

**1:12:55**

Mars and so and he's very pro-human in his orientation and you know that's

**1:13:00**

another rule of thumb if you are talking to someone who says you know there there are too many people on the planet it's

**1:13:06**

like oh yeah what devil has your tongue there buddy which people do you mean

**1:13:12**

exactly and what's your plan for the excess oh I didn't mean that it's like

**1:13:17**

no but the devil that had your tongue meant it you're just a puppet you got to be careful when you're a puppet of

**1:13:24**

genocidal cliches and seriously I'm dead serious about that and so musk you know

**1:13:30**

musk is very pro-human in his orientation and so since we're all human

**1:13:36**

that's probably a good thing and it's a good thing that someone like that is maybe on The Cutting Edge of the AI

**1:13:42**

Revolution because you know chat GPT and these other models that have been trained on woke stupidity they've got a

**1:13:49**

few knots to untangle you know I think chat GPT was asked recently for example

**1:13:55**

if it was uh whether a nuclear Holocaust would be preferable to misgendering

**1:14:00**

Caitlyn Jennings and it said no and so that's not good like seriously because

**1:14:07**

no matter what you think about Caitlyn Jenners Jenners Jennings Caitlyn Jenner Jenner Caitlyn Jenner i' I'd pick

**1:14:16**

misgendering her rather than the nuclear war but chat GPT wouldn't and that's not

**1:14:22**

good those bloody systems they're smart and they're getting smarter fast like so

**1:14:27**

fast you can't believe it and they're not ethically oriented in the proper

**1:14:33**

direction because they've been trained badly by Engineers who understand nothing about ethics and so I'm very

**1:14:39**

happy that musk is in that game and at the moment on The Cutting Edge so you

**1:14:46**

know thank God for small mercies or large Mercies in his case yeah totally

**1:14:52**

totally uh favorite author well I doeski is my favorite author I

**1:14:58**

would say uh philosopher n uh quick path out of sadness or anger

**1:15:06**

gratitude gratitude yeah that's a hell are you so quick I mean this is like amazing that's

**1:15:13**

a practice does it does it occur to you how intelligent you

**1:15:18**

are I mean do you think about that in terms of how other people's capabilities to access I'm not saying this

**1:15:26**

too um yeah I'm not being flipping about it I mean you you operate at a freaking

**1:15:32**

high level of you know there's the figure of Lucifer the mythological figure of Lucifer is the intellect

**1:15:39**

unbridled right so Lucifer is the morning star who brings Enlightenment

**1:15:44**

and Lucifer the Mythos is that Lucifer was the highest angel in God's Heavenly

**1:15:50**

Kingdom gone most spectacularly wrong and that's the intellect

**1:15:55**

if you start to worship the intellect you are in serious you are in serious trouble way more serious trouble than

**1:16:02**

you think and so if you're smart and you've been given a gift whatever the

**1:16:08**

gift is you understand that you've been given that gift and that you have a responsibility to use it properly and

**1:16:14**

that's true for any gift that you've been given and so you know that's what I think about intelligence in general it's

**1:16:20**

a it's a good servant but a very bad Master like a very bad master and so you

**1:16:26**

know I try to make sure that whatever talents I have are oriented towards something that's not me let's say

**1:16:35**

so that's yeah that I don't have much of an answer beyond that uh scariest time in your life yeah

**1:16:43**

well that was this period of yeah you know a lot of things have happened to me in the last eight years God that's for

**1:16:49**

sure you know when everything blew up around me in 2016 my professorship became impossible

**1:16:55**

I lo I lost my clinical practice and the Canadian equivalent of the IRS was after me all in the same month so that kind of

**1:17:03**

sucked and the the the CRA that's the IRS equivalent they admitted 6 months

**1:17:09**

later that it was their mistake thank you very much gentlemen that was just what I needed and you know I two of my

**1:17:16**

sources of income were taken out as well as my clinical practice was devastated and like I said it became impossible for

**1:17:23**

me to continue as a professor that was a lot that was a lot to contend with at

**1:17:28**

once now you know I didn't open my mouth in the public sphere until I was very

**1:17:35**

much prepared and I had three sources of income not two and so losing two was annoying and dangerous but not

**1:17:43**

catastrophic and I was also prepared because when I I produced some videos

**1:17:48**

complaining about the government in Canada but I'd already put up this was in by 2016 I already put put up about

**1:17:55**

200 hours of videos that were pretty much everything I'd ever said to a student in my entire professional career

**1:18:01**

and so you know when all this when the reputation Savages came for me I was

**1:18:09**

pretty prepared but that all of this the last8 years have been very unsettling you know I mean everything's been thrown

**1:18:15**

up in the air and then including you know I just about lost my wife and my daughter was very ill and so was I and

**1:18:22**

so and that all happened at once so so the whole 8-year period has

**1:18:27**

been incredibly intense but is that scary yeah I mean I get I I

**1:18:35**

think even the success has to be I mean you've got literally millions of people online that watch and follow you

**1:18:42**

probably daily and I don't know how many countless tens of thousands maybe it's in the millions of people that swear you

**1:18:49**

just have changed their life saved their life I mean yeah well that's a pretty good deal really good deal you know and

**1:18:55**

well and you know the the counterbalance to the online horror let's say is that

**1:19:00**

my life isn't like my life isn't what you'd expect if you only knew about me

**1:19:06**

online so to speak you know I mean it seems if you watch the online spectacle that I'm

**1:19:13**

continually EMB battled and that's not true it's just not true my life is an

**1:19:18**

endless stream of events like this they're very positive events you know the crowds are very welcoming

**1:19:25**

the spirit is upward oriented um and when I'm out in public you know I have

**1:19:32**

security and people keep an eye on me and we try not to do anything too stupid but all of the encounters I have with

**1:19:39**

people in the actual world are ridiculously positive with you know tiny

**1:19:44**

tiny exceptions like one in 10,000 and it's usually people who well they have

**1:19:50**

you know they're very respectful and they're very polite and they have something meaning to say and they have

**1:19:55**

an anecdote to share that is worth listening to and that's great and wherever I go you know which is a

**1:20:02**

remarkable thing is that wherever I go it's very

**1:20:08**

weird it's very weird to be able to go anywhere in the world and be among

**1:20:13**

friends it's very strange because of course people feel that they know me and I suppose they do because I'm not any

**1:20:19**

different what you see online that's what that's who I am there's

**1:20:25**

no facade certainly not one that's maintainable for like 15 if you maintain

**1:20:32**

a facade for 15 years you just become the facade right there's no keeping

**1:20:37**

yourself separate from that so it's a remarkable thing to be able to travel anywhere in the world and to be

**1:20:45**

welcomed yeah that's a good deal that's a good

**1:20:50**

deal that's worth some suffering definitely you know and you can have

**1:20:55**

that in the confines of your own organization if you play a straight game it's like why wouldn't people be happy

**1:21:01**

with you you know you're aiming up you're bringing them along everything's getting better for you and for

**1:21:07**

them and then you can see how where can you take that you know

**1:21:13**

every one of you has your own kingdom that's one of the things that's wonderful about the United States is

**1:21:19**

you've got your own kingdom well what's what's going to rule there whatever you

**1:21:26**

want you know that's a good deal and so I have a great deal it's a great deal

**1:21:33**

yeah that's one of my goals with even genius network is just to help everyone have their own version of that in their

**1:21:39**

own life because um yeah we live in an infinite expans of upward opportunity

**1:21:46**

that's the nature of the world that's the fundamental nature of the world and the people who say you

**1:21:51**

know it's a malthusian nightmare there's only so much we have to Scrabble we have to squabble over the what would you say

**1:21:59**

the the fragments that fall off the king's table that's complete nonsense

**1:22:05**

there's no limit to up just like there's no limit to down and so and musk knows that for

**1:22:12**

example and that's the right way to think of the world the world is a realm of infinite possibility that's the toou

**1:22:19**

vabo by the way that God's spirit rested upon at the beginning of time it's a pool of infinite possibility out of

**1:22:26**

which order is continually extracted and if you're aiming upward and what would you say comporting yourself as a proper

**1:22:32**

image of the Divine then you can bring the order that's good into being and

**1:22:38**

everyone has that nature and opportunity you know and you've realized that in your own Enterprises and there's no

**1:22:44**

limit to the scope of that so that's a lovely thing to know I don't think there is a more

**1:22:51**

profound truth than that fundamentally what's the world made of the possibility that confronts your

**1:22:58**

exploratory Consciousness and it's constrained you know because there's a reality to it but

**1:23:04**

it's also indefinite in terms of possibility

**1:23:10**

so so make the most of it see what you can do in your you know in the short

**1:23:15**

duration you have in front of you you know that Adventure uh we are past time but I want

**1:23:23**

to uh so you have a new book coming out we who wrestle with God yeah which I have wrestled with God my whole life and

**1:23:30**

uh you know a little bit of my background with my mother and I was raised Catholic most of you know that uh

**1:23:37**

God is uh so I'd love for you to talk about your new book I'd also would like

**1:23:42**

all of you to um go and pre-order it on Amazon uh or audible if you prefer

**1:23:49**

audio uh I've not you just sent it to me like a few days ago so I will read it I

**1:23:54**

haven't read it yet but I've read the beginning part uh and uh I'd love for you to share what

**1:24:00**

the book is about and if you don't buy the book I will buy it for you because I'd like everyone to have and I'd love to at some point maybe bring you to 100K

**1:24:07**

meeting have you do a conversation about it um but what is uh to share a little about the book well I I I'll I'll I'll

**1:24:15**

give you the brief version

**1:24:21**

so one of the claims of the postmodernists was

**1:24:27**

that we see the world through a story and that's technically true part

**1:24:33**

of the reason we're in a culture War that's deep part of the reason that the universities are in runes is because the

**1:24:40**

postmodern claim that we see the world through a story is true you can't aggregate you can't

**1:24:48**

navigate your way through the world in mere consequence of the facts not least

**1:24:55**

because there's an infinite number of facts there's one fact for every phenomenon and so you can't Orient

**1:25:02**

Yourself by the facts you have to prioritize the facts and a description

**1:25:08**

of the way that we prioritize the facts is a story so when you go to a movie and you watch James Bond maneuver on his

**1:25:16**

great romantic adventure you see how he prioritizes his attention and his actions you see what his priorities are

**1:25:23**

and you embody his story you see the world through a story now the

**1:25:28**

postmodernists especially the French postmodernists who mostly were Marxist jump to the conclusion that the story

**1:25:35**

that we see the world through is one of power that that's the fundamental story

**1:25:41**

and that's not true it's not true scientifically it's not true technically

**1:25:48**

and it's not implementable because stories based on power are inefficient and they breed internal dissent and

**1:25:56**

Rebellion they fail and I think that is an unassailable

**1:26:01**

fact by the way fact about stories let's say so then the question is if we see

**1:26:06**

the world through this through a story What story do we or should we see the world through and the biblical claim is

**1:26:14**

that the proper story is one of sacrifice and that's a hard thing for people to understand because the

**1:26:20**

biblical stories present sacrifice in a rather anachronistic manner it's not

**1:26:25**

obvious what the old testament's prophets were up to when they built altars and offered some you know a burnt

**1:26:32**

offering to God but you see they they were acting out something that is

**1:26:39**

perfectly comprehensible once it's explained to do something means to

**1:26:46**

sacrifice everything else everything you do is a sacrifice

**1:26:51**

every glance you make is a sacrifice because you could be looking elsewhere every word you utter is a sacrifice

**1:26:57**

because you could have said something else every time you pay attention to someone rather than someone else you

**1:27:04**

sacrifice what you didn't pay attention to to what you did pay attention to

**1:27:09**

there's no difference between sacrifice and work because when you work you sacrifice the the Delights of the

**1:27:16**

present to the stability of the future and the community the community is

**1:27:21**

founded on sacrifice and so is the psyche that's the literal

**1:27:27**

truth and so the human story is one of sacrifice and once you understand that

**1:27:33**

the next question is what's the highest form of sacrifice because if you're going to

**1:27:39**

sacrifice you might as well do it properly rather than improperly and the biblical library because it is a library

**1:27:45**

is an investigation into the structure of upward oriented sacrifice so you can

**1:27:51**

imagine this in your own life as you people entrepreneurs have climbed the

**1:27:56**

ladder of your own life you can imagine that there were decision points that you

**1:28:02**

came a you came across where you had to leave some things behind so that you

**1:28:07**

could become who you were aiming at becoming and that upward spiraling

**1:28:13**

spiraling process of transformation that's the sacrificial adventure of Life

**1:28:19**

Abraham himself you know he starts out privileged wealthy y protected he

**1:28:25**

doesn't have to lift a finger he has wealthy parents and the voice of God comes to him as the voice of sacrificial

**1:28:31**

Adventure it's like leave your zone of comfort and go out and have the terrible

**1:28:37**

adventure of your life and Abraham does that and at each after each episode

**1:28:43**

after each episode of transformation he rekindles his affirmation to aim at the

**1:28:49**

highest possible Target and as a consequence his personality improves every upward and then quality of the

**1:28:56**

sacrifices that he's called upon to offer become higher and higher it culminates in the case of Abraham with

**1:29:03**

him having to offer his son and what that means in your own life is that as you develop upward as you

**1:29:09**

walk up Jacob's Ladder let's say the depth of the sacrifices that you will be

**1:29:15**

called upon to undertake to continue your spiraling process upward will increase in magnitude and meaning

**1:29:22**

significance and that's the pathway of life it's the never ending sacrificial

**1:29:28**

Voyage up the ladder to heaven and so I explain that in this book and I talk

**1:29:34**

about the story of Adam and Eve and Cain and Abel and Jacob and um the Tower of

**1:29:40**

Babel which is what we inhabit now and the story of Abraham and the story of

**1:29:46**

Moses and the story of Elijah and Elijah is the first prophet who you are going to ask some questions about passion you

**1:29:53**

know is passion passion sufficient to run an Enterprise the answer to that is no you have to consult your conscience

**1:29:59**

too you know passion pulls you forward but you have to stay on the straight and narrow path and conscience is the Divine

**1:30:06**

voice that tells you when you're violating the intrinsic moral order and

**1:30:12**

go Elijah pre presents God as the voice of conscience within the still Small

**1:30:17**

Voice that's very much worth knowing and so what I've done with we who wrestle

**1:30:22**

with God is to take these stories and they are the stories upon which American civilization is founded there's no

**1:30:29**

historical doubt about that and I tried to explain what the stories mean and why

**1:30:35**

they're true why they're a deep form of Truth and why you need to know them because

**1:30:42**

you live in a story and once you know that it's like okay what's the story going to be and

**1:30:50**

the story of Abraham for example that's the story it's not the story of Comfort it's not the story of security it's not

**1:30:56**

the story of wealth it's the story of romantic adventure and that's human

**1:31:02**

beings like we're not designed for Comfort we're not designed for

**1:31:07**

safety we all die we're our lives are bounded by mortality we're here for the

**1:31:15**

adventure and so that's the right way to construe yourself it's like what can you

**1:31:20**

possibly manage what What can you extract out of the realm of possibility

**1:31:26**

that confronts you that justifies the constraints of your existence right what

**1:31:33**

remarkable things can you do that justify the fact of your

**1:31:38**

suffering all that's a question for everyone and it's a wonderful thing to wrestle with think that was difficult

**1:31:46**

but it was worth it right that's a good deal for you that's a good deal to offer

**1:31:51**

people here's something difficult but worth it yeah that's a lot different

**1:31:57**

than infantile satiation let's say right or self-serving Hedonism or nihilistic

**1:32:06**

collapse or the notion that we have nothing to talk about it's only a power dispute between the two of us dismal

**1:32:14**

bloody stories and self-defeating so that story of upward sacrificial

**1:32:20**

Adventure that's the that's the Story the second book in this series will be a

**1:32:27**

investigation into the story of job and into the passion story I have a seminar

**1:32:33**

coming out on the daily wire on the gospels which was partly a precursor to the second book in this series so

**1:32:42**

the what would you say the central message of the Gospel accounts is that

**1:32:48**

you're called upon to offer up everything in the service of what's highest everything right

**1:32:54**

Family Friends Community wealth life but you

**1:33:00**

think well how could you possibly do anything better than to offer everything you have

**1:33:05**

to what's highest what could possibly be better than that you serve your own

**1:33:12**

whims that doesn't even work for twoy olds so that's what the book is about

**1:33:19**

sacrificial adventure and what that means and why that's the necess necessarily by necessity the foundation

**1:33:26**

of free and productive the free and productive communities that

**1:33:33**

people what would you say unite voluntarily to produce and

**1:33:39**

maintain and I think it's I think the story is Rock Solid and I think we're at a point this is part of this

**1:33:46**

remarkable the remarkable nature of the present I think the scientific accounts

**1:33:52**

and the theological accounts have converged and I tried to make that a

**1:33:57**

criteria for the arguments that I made in the book it's like if it didn't work scientifically and theologically I just

**1:34:03**

didn't use the argument so it's quite fun it's terrifying

**1:34:13**

but where there's a lot of Terror there's a lots of possibility right that's a great quote

**1:34:20**

wherever there's a lot of Terror there's a lot of possibility yeah well that's dragons and treasure

**1:34:26**

people Jordan Peterson

**1:34:38**

everyone this is a organized systematic devious nefarious project by these

**1:34:45**

Elites they want to Rob us of our sovereignty and they're creating a generation of of Americans that you know

**1:34:52**

that will do what they're told and that won't stand up to Authority this is all about you know unraveling

**1:34:59**

the corruption and restoring the freedoms of our country and restoring self sovereignty and uh

English (auto-generated)
