---
title: "To Debate Better"
author: "notes by DK"
date: "14 Nov 2024"
---

## Interviewer

You are so good at debates and making your case and backing it up with you know not only your own view but stats.

I mean you have this incredible ability to not only bring up resource that you know so much. How does one develop that skill?

## Interviewee

I don't debate to win.

I'm not particularly interested in winning, I stopped doing that when I was in my 20s when I learned that that was a counterproductive strategy.

What I'm trying to do when I speak is to say what I believe to be true and that's a long-term victory like the truth is a long-term strategy.

All I'm trying to do is to formulate my words as clearly as I possibly can.

If you can learn to do this, it's really worth learning, although it's very unsettling when you start.

You want to feel out whether or not the words that you're saying are firm.

Like walking on `Foundation Stones` and you can sort of feel them out as you make your way that's how Moses went across the Red Sea.

## The Interview

<https://www.youtube.com/watch?v=pKYiKQ-tmUQ&t=1335s>
