---
title: "Complementary"
author: "DK"
date: "2025-01-03"
categories: [parents]
---

There are certain pair of words in English with a similar sounds.

-   affect / effect
-   discrete / discreet
-   principal / principle
-   complementary / complimentary

---

My parents marriage was not always complimentary or complementary.
There marriage was arranged by older relatives.
They married 5 years after the war.

They started with next to nothing.
Together they married off and helped to get started in life, 3 younger siblings of my father.
Consequently, they paid off those debts, only after my father had a well-paying job in Vietnam, 8 years after the marriage.

---

58. Another prominent aspect of gender theory is that it intends to deny the greatest possible difference that exists between living beings: sexual difference. This foundational difference is not only the greatest imaginable difference but is also the most beautiful and most powerful of them. In the male-female couple, this difference achieves the most marvelous of reciprocities. It thus becomes the source of that miracle that never ceases to surprise us: the arrival of new human beings in the world.

https://press.vatican.va/content/salastampa/en/bollettino/pubblico/2024/04/08/240408c.html



