---
title: "Let's Run"
author: "DK"
date: "2025-01-07"
draft: yes
categories: [code]
---

Sometimes, Sister K and I, use pass code to communicate.

Depending on the day and her mood she responds with

-   No expression, just a smile.
-   Go ahead, have fun and comeback soon
-   OK, let's go together. Where to?

The password we use is `도망가자.`

Which can be interpreted as "let's run away" or hide, or even escape.

------------------------------------------------------------------------

Early in our marriage, weekend meant a clash of will.

I would like to go visit places, Sister K would rather stay home.

Even though I usually prevailed, it was not a mutually enjoyable weekend.

------------------------------------------------------------------------

After decades of marriage, we now agree.

Staying home is the best option.

------------------------------------------------------------------------

What about hiding or escaping from life.

Where would it lead us?

Is it temporary?

Any escape from reality means, we will return.

Even though, the thought of escape is thought of more often.

Not the greatest verbal communicator

It is a way for us to communicate how our day is going.

------------------------------------------------------------------------

Instead

Finally made transition to face reality

By facing reality, one matures, one gains skills to overcome the next challenge.

It is the ultimate role playing game, ever devised, the game of telestial life.

Manager during expat years, his go to phrase was. Things aren't as bad as it seems nor is it as good as it seems.

------------------------------------------------------------------------

Learned about the TOC via the book The Goal by Eliyahu Goldratt. Maximize bottleneck.

-   **Identify the Constraint**: Determine the system's bottleneck.
-   **Exploit the Constraint**: Maximize the throughput of the bottleneck without significant investment.
-   **Subordinate Everything Else**: Align all other processes to support the constraint.
-   **Elevate the Constraint**: Increase the capacity of the constraint if needed.
-   **Repeat the Process**: Once a constraint is resolved, another will emerge—continue improvement.

Not the greatest verbal communicator

Sister K and I use passcode once in a while.

Depending on her mood she responds with

-   No expression just a smile.
-   Go ahead, have fun and comeback soon
-   OK, let's go together. Where to?

The passcode is 도망가자

It is a way for us to communicate how our day is going.

Finally made transition to face reality

Manager during expat years, his go to phrase was. Things aren't as bad as it seems nor is it as good as it seems.

------------------------------------------------------------------------

Learned about the TOC via the book The Goal by Eliyahu Goldratt. Maximize bottleneck.

-   **Identify the Constraint**: Determine the system's bottleneck.
-   **Exploit the Constraint**: Maximize the throughput of the bottleneck without significant investment.
-   **Subordinate Everything Else**: Align all other processes to support the constraint.
-   **Elevate the Constraint**: Increase the capacity of the constraint if needed.
-   **Repeat the Process**: Once a constraint is resolved, another will emerge—continue improvement.

Not the greatest verbal communicator

Sister K and I use passcode once in a while.

Depending on her mood she responds with

-   No expression just a smile.
-   Go ahead, have fun and comeback soon
-   OK, let's go together. Where to?

The passcode is 도망가자

It is a way for us to communicate how our day is going.

Finally made transition to face reality

Manager during expat years, his go to phrase was. Things aren't as bad as it seems nor is it as good as it seems.

------------------------------------------------------------------------

Learned about the TOC via the book The Goal by Eliyahu Goldratt. Maximize bottleneck.

-   **Identify the Constraint**: Determine the system's bottleneck.

-   **Exploit the Constraint**: Maximize the throughput of the bottleneck without significant investment.

-   **Subordinate Everything Else**: Align all other processes to support the constraint.

-   **Elevate the Constraint**: Increase the capacity of the constraint if needed.

-   **Repeat the Process**: Once a constraint is resolved, another will emerge—continue improvement.

    Not the greatest verbal communicator

    Sister K and I use passcode once in a while.

    Depending on her mood she responds with

    -   No expression just a smile.
    -   Go ahead, have fun and comeback soon
    -   OK, let's go together. Where to?

    The passcode is 도망가자

    It is a way for us to communicate how our day is going.

    Finally made transition to face reality

    Manager during expat years, his go to phrase was. Things aren't as bad as it seems nor is it as good as it seems.

    ------------------------------------------------------------------------

    Learned about the TOC via the book The Goal by Eliyahu Goldratt. Maximize bottleneck.

    -   **Identify the Constraint**: Determine the system's bottleneck.
    -   **Exploit the Constraint**: Maximize the throughput of the bottleneck without significant investment.
    -   **Subordinate Everything Else**: Align all other processes to support the constraint.
    -   **Elevate the Constraint**: Increase the capacity of the constraint if needed.
    -   **Repeat the Process**: Once a constraint is resolved, another will emerge—continue improvement.

Not the greatest verbal communicator

Sister K and I use passcode once in a while.

Depending on her mood she responds with

-   No expression just a smile.
-   Go ahead, have fun and comeback soon
-   OK, let's go together. Where to?

The passcode is 도망가자

It is a way for us to communicate how our day is going.

Finally made transition to face reality

Manager during expat years, his go to phrase was. Things aren't as bad as it seems nor is it as good as it seems.

------------------------------------------------------------------------

Learned about the TOC via the book The Goal by Eliyahu Goldratt. Maximize bottleneck.

-   **Identify the Constraint**: Determine the system's bottleneck.
-   **Exploit the Constraint**: Maximize the throughput of the bottleneck without significant investment.
-   **Subordinate Everything Else**: Align all other processes to support the constraint.
-   **Elevate the Constraint**: Increase the capacity of the constraint if needed.
-   **Repeat the Process**: Once a constraint is resolved, another will emerge—continue improvement.
