---
title: "Talents and Stars"
author: "DK"
date: "2025-02-07"
draft: yes
categories: [society]
---

My mom, 황현실, had a wide ranging interest that separated her from other Koreans of her generation.

However, she did have one common interest.

She knew a lot about Korean singers, movie stars, and one in a drama lead roles.

Not just those from her generations but young generations as well.

Whereas, I had trouble keeping up with similarity of names and roles as well as drama series, she had a knack for remembering and categorizing away stars.

She didn't keep a written note either.

------------------------------------------------------------------------

What I appreciated about her knowledge of these individuals is that she can add human side to each artists report.

------------------------------------------------------------------------

As people depart, the focus is on the death and what ifs.

My mother was able to provide reason and understanding.

Rather focus on the positive aspect of their lives

------------------------------------------------------------------------

謝謝大家的關心！新年期間，我們全家來日本旅遊，我最親愛善良的姊姊熙媛，因得了流感併發肺炎，不幸地離開了我們。感恩這輩子能成為她的姊妹，彼此照顧、相伴，我會永遠感激她、懷念她！珊～一路好走！永遠愛你 together remember forever。
