---
title: "Tumen River"
author: "DK"
date: "2024-12-30"
draft: yes
categories: [remembrance]
---

A nation of, "...sorrows and acquainted with grief."

------------------------------------------------------------------------

My maternal grandmother,김연화, sang well. Thus, I was told by mom.

Growing up I never heard her sing, however.

Her husband, 황운학, who didn't sing well would at a gathering would ask her to sing.

Her go to number was, 눈물젖은 두만강 Tumen River Elegy (圖們江悲歌)

When grandfather was alive, the song was a rendition of a popular song, and a reflection on past relationships.

When grandfather passed away, it must have been difficult to hear the song again.

------------------------------------------------------------------------

Found a recording of my cousin singing the same song. That cousin and I are same age, born a month apart. Her father was a great singer, like his father was.

Her voice has that quality that takes one back to olden days. A lyrical, story telling quality within her voice.

Hearing the recording, made 25 years, stored in cloud and played through the car's bluetooth made me cry.

두만강 푸른 물에 노젓는 뱃사공\
흘러간 그 옛날에 내 님을 싣고\
떠나든 그 배는 어데로 갔소\
그리운 내 님이여 그리운 내 님이여\
언제나 오려나

On the blue waters of the Tumen River, a boatman rows,\
In those days long past, carrying my beloved.\
Where has that departing boat gone?\
Oh, my dearest one, my dearest one,\
When will you return?

Made me think of departed ones. Their memories that lingers. Asking the same question,

Also, things that have been altered and will not return to original state. Innocent belief, faith.

강물도 달밤이면 목메여 우는데 님 잃은 이 사람도 한숨을 지니 추억에 목메인 애달픈 하소\[5\] 그리운 내 님이여 그리운 내 님이여 언제나 오려나 님가신 강 언덕에 단풍이 물들고 눈물진 두만강에 밤새가 울면 떠나간 그님이 보고 싶구나 그리운 내 님이여 그리운 내 님이여 언제나 오려나

On the blue waters of the Tumen River, a boatman rows, In those days long past, carrying my beloved. Where has that departing boat gone? Oh, my dearest one, my dearest one, When will you return?

Even the river weeps hoarsely on moonlit nights, And I, who have lost my love, sigh deeply. With memories that choke my heart, this sorrowful lament. Oh, my dearest one, my dearest one, When will you return?

The hills by the river, where you once stood, are painted with autumn leaves, And when the weeping cries of the night birds echo over the tear-streaked Tumen River, I long to see my departed love. Oh, my dearest one, my dearest one, When will you return?
