---
title: "Dear God"
author: "DK"
date: "2024-09-27"
draft: yes
categories: [letters]
---

Dear God thank you for ever letting me have this experience on this earth grateful for all the challenges and people that I've met so far I could not have imagined where I am from where I started looking back I truly have been blessed from my early age I had people around m that talked about you what I should do and try to be like you and they include it my mother both of my grandmothers although I never got to meet my grandparents my grandfathers I could learn from them nevertheless and I also have experiences of those that try to be far away from you as possible but I've also seen people that have changed and excepted as that be no journey has been full of kindness shown by others now I want to be the giver so I want to thank you today for my parents who they were what they taught me likewise thank you for sending me my companion helper for she truly help me to pick up a better person or a new person also thank you for sending us additional spirits to help with us individual they are I am grateful to see them start their own lives on the covenant make starting a new world for themselves grateful that we have a chance to work and live under the freedom that are given protected ultimately allowing us to exercise that choice and shape Rome teacher thank you for the knowledge there are given repealed a little at a time it is that enough for me and others so I want to be in there today and water near me and reveal what actions I can take to be a more service to the others it is my prayer on this day 26 day of September your road 2020 for a man
