---
title: "Work Approaches"
author: "DK"
date: "2025-01-25"
draft: yes
categories: [work]
---

When I work with the Japanese team in I was excited I was excited to find out what makes Japanese product more consistent but aside from the speaking with the person from one hour I never got a detail from them in the six years that I work with them but I felt like the cutter KT8 presenter who when he asked a Toyota person various questions the Toyota person responded by saying why are you asking us all these questions why don't you figure out what works for you and implement that in a similar way to Japanese Tim answer we don't try different things off we just try to make the target now as a response similarly

One other time we were discussing how to set up a training K process was extrusion and we need extrusion engineer Japanese side suggested to your trading American sites at six weeks we wound up having a six week training Japanese approaches to hire a person and then train sufficiently for them to become a master at it whereas American approaches to hire a professional proficient person to become ready extrusion ready which ones better I'm not sure
