---
title: "Marantz DV 12S1"
author: "DK"
date: "2024-09-09"
categories: [audio]
---

THE MARANTZ DV 12S1 IS A HIGH-PERFORMANCE REFERENCE SERIES DVD/CD PLAYER. THE DV 12S1 IS COMPATIBLE WITH DTS, DOLBY DIGITAL, DVD AUDIO AND INCLUDES THX ULTRA CERTIFICATION. IT WAS JUST SERVICED BY MY VETERAN TECH AND EXHIBITED NO PROBLEMS, PERFORMS LIKE NEW. THIS \$2,600 LIST PLAYER DELIVERS AUDIO DETAIL AND DYNAMICS FAR BEYOND CONVENTIONAL PLAYERS.

-Audiogon,

If this item was introduced today, it would be sold at \$4500

\$***2,600 in 2002 is worth \$4,545.88 today***

This unit does have a drawer issue.

It has a mind of its own.

There is a cheap fix (\$5!) for your problem, the same one I just dealt with. There is a plastic gear which makes the tray slide in and out. It wears with use and exposure to our polluted atmosphere. Look on ebay for a replacement, different versions for different transports. You can replace the gear yourself, or buy it off ebay and take it with your player to a tech.

---

Suggested selling price: \$300

Ebay had a same item, no remote, same drawer issues.

<https://www.ebay.com/itm/395063597575>
