---
title: "Business Card"
author: "DK"
date: "2024-11-19"
draft: yes
categories: [audio-amplifier]
---

During the holiday break, I tried to recall names of people that helped me and influenced me over the years.

I have heard that typically, a person meets or knows about a thousand person in their lifetime.

Scores of names came to mind almost immediately.

Then I ran into trouble.

I could remember their roles and places I met them, and remember them by sight.

But I could not recall their names.

For example, the head of quality or regulatory function for Asia Pacific.

She was from Singapore, and made several visits to 구미, at times during winter months.

---

I was able to recall more names, when I broke my life into segments.

-   East Coast days in Maryland.
-   Mission days in California.
-   Education at Brigham Young University.
-   Managers and co-workers at various companies
-   대구/구미 Years
-   YSA days, 1990s and 2020s.

------------------------------------------------------------------------

## Name Card Holder to the Rescue

Found 3 books from world travelling days.

Found Shimizu san who met us at the Komatsu Airport

Also Ginny C. who visited us along with Chee Huat K.

Reading the name, role and place along with few dates that were hand written triggered many memories.

I plan to contact them and thank them for guiding me in this life.

---

Business file is a 2" x 3" card contains

-   who we are

-   what we do to make a living

-   where is the place of work

-   ways to contact us

Looking at the card made me reminisce about old days as well as think ahead

-   what would the card say, after the vocation or career has ended.

At the end of our temporal life

-   what would the card, or the grave marker say at the end of our lives.

What will be in our heart, mind and spirit is far more important.

But as our physical abilities decrease and memories fade, it is good to have physical markers and name cards to remind us of our associations; before, here and now and hereafter.

## Keep in Touch

How do we do this effectively.

## Last Name Holding Place

Grave marker is the remnant that we live behind in this life.

However, the most fundamental and lasting memories will be in the mind and heart of people we interacted with.

Wonder what kind of social networking is utilized in the next sphere?

명함 名銜 or 名刺

was widely used.

According to Korean Wiki site,

> The first business card is known to have been made from bamboo cut in ancient China, and was called Mingzi.

The last and enduring name card is the
