---
title: "Mission Gifts"
author: "DK"
date: "2024-10-23"
draft: yes
categories: [mission]
---

I found myself on my mission

Sister K, on the other hand, found her calling in life.

Move from DC suburb to LA basin was a big change for me.

I am a Korean-American LDS

She served with her sister for a month during Christmas, who was on her way to Korea and waiting on a VISA.

During a stretch where she was rejected by most everyone, she made a vow and to her.

> Whoever comes to our home will be welcomed in. In addition, there will be a warm cookies awaiting them

Sister K bowed to serve all those that came to the home as a missionary - she has kept that promise.

---

By today's standard, or any other standard for that matter, I was not a well prepared missionary

Compensating for lack of preparation was my intent, pure

My language skill matched my preparation level, a novice.

Regardless, people invited me in and listened to our messages.

More accurate, looking back, to say, I got sympathy look and reception

I learned that I am a person of worth.

A Korean descendant, along with 100s of thousands of other Koreans.

Decide to be a member of the Church

Thankful for the people of LA for welcoming me and giving me a chance to discover who I am.

and my potential role as a Korean American Latter-day Saint.

Walked the streets of Western Avenue and Olympic Blvd

From Oxford to Harvard.

We found our role and who we are by serving in LA.

To what extent we were serving our God or our fellowmen, we are not sure.

> And behold, I tell you these things that ye may learn wisdom; that ye may learn that when ye are in the service of your fellow beings ye are only in the service of your God. (Mosiah 2:17)

We do know that the person most benefitted by that service was ourselves.
