---
title: "Accordion Doctor"
author: "DK"
date: "2024-09-15"
draft: yes
categories: [intro]
---

If my mom had her wish, I would have been an accordion playing doctor

Since she recognized my lack of interest or talent she changed her approach

\

She put the curse of the honey seller

\

She predicted that my father would go overseas and that I would learn as much as I wanted

\
\
\
\

As the son got up to conduct a memorial for his father, who passed away in 2003, he remarked.

This is not some kind of re-incarnation.

This is the son.

\

But he looked just like his father, during the prime years that he was serving as a leader in Korea and thereafter in Provo.

\

At certain age sons start to look like their fathers.

Perhaps because they start to feel the weight of being a father and husband themselves.

Or perhaps sons experiences same trials that shaped their father’s lives

Thereby starting to see things from their father’s perspective and even start to think in the same manner.

\

The timing of this varies from individual to individual but it probably begins around mid-to-late 40s. – after raising the next generation beyond their teenage years.

\

—

\
\

As a Korean American need to keep track of more things.

\

The less you speak, better understood you are.

\

Romanticism of hometown

This life is full of disappoints, perhaps next life is also.

Is there a next life.

\

Taste coordinator runs in the family

\

One quick way to find your influence in the family is to invite more people to your home than you have beds and bedrooms.

\

We had such occasion during a wedding.

Some chose to go the Air BnB route or a traditional hotel stay.

Some however, chose the most traditional way of staying with relatives.

\

Which started which visiting family gets which bedrooms and who gets to sleep on the floor versus beds.

\

Well, I missed the cut on both and wound up sleeping on the floor.

The mat I was to sleep on was about 30” by 72” (I measured since it looked kind of narrow).

\

Then I got thinking, the size of the mat and the material seemed familiar.

Yes, it was similar to a business, lie flat, offerings for long distance flights.

\

There was a time when I would look forward to long flights and sit/lie down on these beds in the sky.

\

How much has my stock fallen.

\

Actually, spent first 10 years of life, sleeping on the floor with little to no cushions.

Even when we moved to a “modern” home we didn’t have indoor plumbing.

No telephones or television 

Those came about the time I turned 10.

\

We were one of the first to get them and neighbors came by to check them out.

\

In addition no one we knew had a car and we walked everywhere, after city buses dropped off at the closest location.

\

My world seemed endless but it was only 20\~30 mile radius

\
\

Approximately \$100/hour for the privilege of flying the business class.  Oh it did move 500\~600 miles per hour as well.

\

This time around, I was few inches off the ground.  No need to worry about falling off.  The wooden floor would catch me.  But it was colder to the ground.

\

<https://m.blog.naver.com/starcube777/221827259444>

\

<https://www.kidshankook.kr/news/articleView.html?idxno=5510>

\

온돌(溫突)

\
\

—

\

I get a chance to turn them,Official calendar turner

\

One of the advantage of working for a Japanese company affiliate is all the sweets people bring following a business treat

\

Also the beautifully crafted calendars every 2 months.

As I was turning Sep/Oct into Nov/Dec. I noticed that the place depicted seemed familiar.

Yet the name, i didn’t recognize.

\

Did an internet search.

\

A name is a designation 

\

—

\

"...it is no exaggeration to say that you gave her another decade of joyous life through your kindness and sincere friendship. "   

\

This applies to my parents as well.

\

The community at the end of my parent’s life

\

I had another community at the beginning of our lives in US
