---
title: "Korea Nationwide Devotional"
author: DK
date: "2024-09-08"
categories: [devotional]
---

Presiding : Elder Quentin L Cook\
Conducting : Elder Christopher H Kim

-   Date/Time: Saturday, September 7, [6:00](https://www.youtube.com/watch?v=9CER2naM3c4&t=360s) - 7:30 pm
-   Place: Gangnam Ward, Seoul South Stake
-   Attendees: Members and Their Friends
-   Main Link - <https://www.youtube.com/watch?v=9CER2naM3c4>

## Program

Intro: [35:28](https://www.youtube.com/live/9CER2naM3c4?si=ateqCaKhdtnE1udH&t=2128)

Choir Singing: [43:00](https://www.youtube.com/live/9CER2naM3c4?si=phuylGBJOw-Ez9G6&t=2580)

Sister 홍성미: [49:00](https://www.youtube.com/live/9CER2naM3c4?si=aZ2153d8lFKomgtL&t=2927)

Elder 김현수: [53:00](https://www.youtube.com/live/9CER2naM3c4?si=AYEZ92Vtx3kwqzHE&t=3157)

Sister Jacqueline Palmer: [56:00](https://www.youtube.com/live/9CER2naM3c4?t=3360s)

Elder S Mark Palmer: [1:03:00](https://www.youtube.com/live/9CER2naM3c4?si=fiLkzB-LO8XbT4ch&t=3781)

Intermission Hymn: [1:18:15](https://www.youtube.com/live/9CER2naM3c4?si=cnZOBY_34NDRU0j3&t=4693)

Sister Mary Cook: [1:22:15](https://www.youtube.com/live/9CER2naM3c4?si=QR2IXhGw3crs5ZIl&t=4936)

Elder Quentin L Cook: [1:34:00](https://www.youtube.com/live/9CER2naM3c4?si=MMAYNIelPVQ2I6tj&t=5634)

Closing: [2:05:15](https://www.youtube.com/live/9CER2naM3c4?si=BMWBo6bD8bq_lmiu&t=7516)

------------------------------------------------------------------------

Build Zion in your home and hearts

Be an example in the community

Have your vision on the temple

Fulfillment of a prophecy in D&C 90

**11** For it shall come to pass in that day, that every man shall [hear](https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/90?lang=eng&clang=eng&id=11,15#note11a) the fulness of the gospel in his own tongue, and in his own [language](https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/90?lang=eng&clang=eng&id=11,15#note11b), through those who are [ordained](https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/90?lang=eng&clang=eng&id=11,15#note11c) unto this [power](https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/90?lang=eng&clang=eng&id=11,15#note11d), by the administration of the [Comforter](https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/90?lang=eng&clang=eng&id=11,15#note11e), shed forth upon them for the [revelation](https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/90?lang=eng&clang=eng&id=11,15#note11f) of Jesus Christ.

**15** And set in order the churches, and [study](https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/90?lang=eng&clang=eng&id=11,15#note15a) and [learn](https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/90?lang=eng&clang=eng&id=11,15#note15b), and become acquainted with all good books, and with [languages](https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/90?lang=eng&clang=eng&id=11,15#note15c), tongues, and people.

And Acts Chapter 2

^**8**^ And how hear we every man in our own tongue, wherein we were born?

^**9**^ Parthians, and Medes, and Elamites, and the dwellers in Mesopotamia, and in Judaea, and Cappadocia, in Pontus, and Asia,

^**10**^ Phrygia, and Pamphylia, in Egypt, and in the parts of Libya about Cyrene, and strangers of Rome, Jews and proselytes,

^**11**^ Cretes and Arabians, we do hear them speak in our tongues the wonderful works of God.

^**12**^ And they were all amazed, and were in doubt, saying one to another, What meaneth this?

------------------------------------------------------------------------

+---------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Korean                                                                                                  | English                                                                                                                                                                                                                                                                                                                                                               |
+=========================================================================================================+=======================================================================================================================================================================================================================================================================================================================================================================+
| 우리 모두가 사랑하는 하나님 아버지의 자녀이고 또 우리가 바라봐야 할 분 주님임을                         | We are all children of our beloved Heavenly Father and the Lord whom we must look up to.                                                                                                                                                                                                                                                                              |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 우리 사랑하는 우리 연합 독신 성인 여러분들을 통해서이 아름다운 노래를                                   | Thank you for allowing us to feel that truth once again through this beautiful song, through our beloved United Single Adults Choir.                                                                                                                                                                                                                                  |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 통해서 또 한번 그 진리를 느낄 수 있으 감사합니다 너무 아름다운 노래였어요                               | It was such a beautiful song. Thank you.                                                                                                                                                                                                                                                                                                                              |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 감사합니다음 지난 주말에 저희 남편하고 저는 그 동경의 한 스테이크                                       | Last weekend, my husband and I had the opportunity to attend a stake conference in Tokyo we also had the opportunity to visit three sisters and their families.                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 대회에 참석할 수 있는 기회가 있었습니다 어 그 또 저희들이 세분의                                        | coincidentally, all three sisters were terminally ill. But, while visiting, I saw that the sisters understood Heavenly Father's perfect plan of salvation and endured this hardship with faith in power, so I was so touched to see them so joyfully.                                                                                                                 |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 그 자매님들을 또 그 가족들을 방문할 수 있는 기회가 있었는데 어 공교롭게도 그 세분의 자매님들이 다       | one of the sisters had cancer cells that had spread throughout her body, and the doctor said that there was nothing more she could do, so she had only about two months to live.                                                                                                                                                                                      |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 말기암 환자였어 근데                                                                                    | So we visited her. So now, I think she was so tired that she couldn't even come to see us. I was worried about what to do if it was hard, so I went in the door, but that sister was smiling so brightly and saying that it was dinner time in the kitchen, so she was diligently and happily preparing food for us.                                                  |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 방문하면서 그 자매님들이 하나님 아버지의 완전한                                                         | As I looked at the sister, she said that of course she was physically and mentally tired, but she was thinking about how she could serve and help others in this situation.                                                                                                                                                                                           |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 구원의 계획을 이해하고 권력에 위한 믿음을 믿음으로이 어려움을 정말 하게                                 | She said that her husband was in charge of the missionary work, and that her husband helped her diligently, and that two baptisms had come out recently.                                                                                                                                                                                                              |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 이렇게 잘 기쁘게 견뎌 내시 그런 모습을 보고 너무 큰 감동을 받았습니다 어 그 중에 한                     | She said that she was so happy because she was living in joy, and she felt that her body was becoming more energetic and better. When I saw that sister, who was really struggling, did not get frustrated by her own difficulties, but instead reached out to others,                                                                                                |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 자매님은 이제 그 암세포가 모든 몸 면제 다 퍼져서                                                        | I thought that she was a person who really resembled the Lord. At the general conference last October, I would like to share a word that Elder Quentin Cook said.                                                                                                                                                                                                     |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 의사가 이제 더 이상 손을 쓸 수 없다라고 해서음 한 두 달 정도 생존할 수                                  | It was one of my favorite tables. It was about following Christ in peace. He spoke about where it is possible to be, and he said this: We do not know all the answers to what happens in life, but we do know important principles that will help us face realization, hardship, and adversity with faith and confidence in the bright future that awaits each of us. |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 있는 기간이 두 달 정도밖에 없다라는 그런 선고를 받으셨다는 말을 듣고 저희가 방문을 했어요 그래서 저희는 | I testify that those who follow Christ in peace will find personal peace both in this life and in our glorious reunion in heaven. I was strengthened by the words of the State of the Union.                                                                                                                                                                          |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 이제 생각에 자매님이 너무 힘드셔서 저희 방문조차 봤 지 못할                                             | I testify that even in this climate, when we look to Jesus Christ and focus on the peace and healing He offers, all the difficulties and hardships we face can be transformed into joy and hope. I testify that our Heavenly Father knows and loves us all, and that Jesus is my Redeemer and Savior. In the name of Jesus Christ, amen.                              |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 정도로 그렇게 힘드시면 어떡하나 그렇게 걱정을 하면서 문에 들어섰는데 그                                 |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 자매님께서 너무 밝게 웃으시면서 주방에서 저희가 이제 저 저녁 시간이 되었거든요 그래 저희를 저녁을 이제  |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 어 준다고 열심히 기쁘게 음식을 만들고 계시더라고요 자매님을 보면서 그                                   |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 자매님이음 물론 육체적으로 많이 힘들고 정신적으로 힘들지만이 상황에서 내가 더 다른 사람들에게 더 어떻게 |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 내가 봉사하고 도와줄 수 있는지 그걸 생각하고 계신다고                                                   |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 말씀하셨고 남편이 와대 선교 책임 자신인데 남편 열심히 도와서 또 얼마 전에는 그 두                       |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 명의 baptism 나왔다 이렇게 말씀하시면서 어 너무 기쁘니까 본인이 기쁨                                    |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 가운데서 생활하니까 몸에 활력이 생기고 몸이 좋아지는 걸 느끼고 있다라고 말씀하셨어요 제가 그 자을       |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 보면서 그 정말 힘든 가운데에서도 그 자기의 그 어려움에 좌절하지                                         |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 않고 오히려 다른 사람에게 손을 뻗치고 내미는 그런 자매님을 보면서                                       |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 정말 주님을 닮는 사람이다라고 생각을 했습니다 어 지난 10월 연차대회에서                                 |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 어 Quentin Cook 장로님께서 어 해 주신 말씀을 좀 전하고                                                  |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 싶습니다 제가 정말 좋아하는 탁 중에 하나였는데 어 화평한 중에 그리스도를 따르는                         |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 자가 되는 곳에 대해서 말씀해 주셨는데 이렇게 말씀해 주셨습니다                                          |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 우리는 삶에서 일어나는 일에 모든 답을 알지는 못합니다 그러나 우리 각자를 기다리고 있는 밝은 미래에      |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 대한 믿음과 확신으로 실현과 고난과 역경을 맞서게 해주는 중요한 원리들을                                 |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 알고 있습니다 화평한 중에 그리스도를 따르는 자들은 이생에서 또한 하늘에서                               |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 영광스러운 재회를 할 때 개인적인 평안을 찾을 것임을 간증합니다 저는                                     |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 국정 말씀을 듣고 어 힘을 얻었습니다 저희들의 삶에 이런 풍                                               |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 속에서도 우리가 예수 그리스도를 바라보고 그분이 주시는 평안과 치유에                                    |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 우리가 집중할 때 저희들이 겪는 모든 어려움과 그런 고난이 기쁨과 희망으로                                |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 변할 수 있다는 것을 간증드립니다 저는 하나님 아버지께서 저희 모두를 알고 계시고 사랑하시며 예수님께서   |                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                       |
| 저의 구속 주이고 구세 주시면 간증드립니다 예수 그리스도의 이름으로 전해드립니다 아멘                    |                                                                                                                                                                                                                                                                                                                                                                       |
+---------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

+--------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Korean                                                                                                 | English                                                                                                                                                               |
+========================================================================================================+=======================================================================================================================================================================+
| 먼저 이렇게 여러분들에게 제 간증을 전할 수 있는 길를 주시는 Cook 장로님께 감사를 드립니다              | First, I would like to thank the director for giving me the opportunity to share my testimony with you all.                                                           |
|                                                                                                        |                                                                                                                                                                       |
| 아 얼마 전에 한한 2주 전에 그 저희 자녀 중에 한 명이 저에게 어                                         | Ah, a couple of weeks ago, one of our children asked me,                                                                                                              |
|                                                                                                        |                                                                                                                                                                       |
| 아버지 아버지는 이제이 새로운 부름을 받고 봉사하시는 지난 몇 개월간                                    | What have I learned in the past few months while serving in this new calling?                                                                                         |
|                                                                                                        |                                                                                                                                                                       |
| 무엇을 배 배웠습니까고 저한테 물어보더라고요 그 제가 곰곰히 생각을                                     | I had a chance to think carefully.                                                                                                                                    |
|                                                                                                        |                                                                                                                                                                       |
| 볼 수 있는 기회가 있었습니다 과연 지난 몇 달간 제가이 새로운 부름에서 봉사하면서 과연 나는 을 배웠는가 | What have I learned in the past few months while serving in this new calling?                                                                                         |
|                                                                                                        |                                                                                                                                                                       |
| 그때 생각났던 바로 구절이 바로 그 니파의 후서 여러분 잘 아시는 4장                                     | The verse that came to mind was the verse in 2 Nephi 4:3 that you all know well. I now look at the living prophet, seer, revelator, my synagogue,                     |
|                                                                                                        |                                                                                                                                                                       |
| 3절의 말씀입니다 제가 이제 살아계신 선지자 선견자 계시자 이제 제 회당                                  | and also at Elder Cook, who is with us today, and the general officers of the 12 Apostles, and the presidents of the civic garden,                                    |
|                                                                                                        |                                                                                                                                                                       |
| 당과 그리고 또 오늘 저희들과 함께하고 계시는 우리 쿡 장로님이 비롯해서 어 12사도 정원의 어 우리        | and how much they                                                                                                                                                     |
|                                                                                                        |                                                                                                                                                                       |
| 사도님 그리고 시민 정원의 회장님 회장당선 있는 총관리 군들의 모습들을                                  | have learned every day and every hour and every moment. Nephi                                                                                                         |
|                                                                                                        |                                                                                                                                                                       |
| 바라보면서 그분들이 매일매일 그리고 그 시간시간 그 때 그때마다 그분들이 얼마나이                       | gave me a glimpse of His heart. In verse 34,                                                                                                                          |
|                                                                                                        |                                                                                                                                                                       |
| 34절에 바로 그 고대의 몰의 예언자였던 선지자였던 니파이가                                              | He said to them, Lord, I have trusted in Thee, and I will                                                                                                             |
|                                                                                                        |                                                                                                                                                                       |
| 저들에게 주해 주신 그분의 마음을 제가 배울 수가 있었습니다 34절에                                      | trust in Thee forever. I will not put my trust in the arm of flesh, for I know that cursed is he who puts his trust in flesh.                                         |
|                                                                                                        |                                                                                                                                                                       |
| 그분은 저희들에게 주여 내가 주를 의뢰 하였사오니 내가 또                                               | Yea, cursed is he who puts his trust in man, who makes flesh his arm.                                                                                                 |
|                                                                                                        |                                                                                                                                                                       |
| 영원히 주를 의뢰하다 내가 육신의 팔에 나의                                                             | These servants of the Lord, hour by hour,                                                                                                                             |
|                                                                                                        |                                                                                                                                                                       |
| 신뢰를 두지 아니하리니 이는 육신의에 자기의 신뢰를 두는 자가 저주를 받는 줄 내가 니이다                | They do not rely on the arm of man, but they do not rely on the arm of life,                                                                                          |
|                                                                                                        |                                                                                                                                                                       |
| 참으로 사람에게 자기의 신뢰를 두는 자 육신으로 자기의 팔을 삼는 자는                                   | but they always rely on the Lord, they trust in Him, they ask for His help. I have                                                                                    |
|                                                                                                        |                                                                                                                                                                       |
| 저주를 받았나이다이 주님의 종들은 매시간                                                               | watched them. There are so many things in this world that teach us to rely on the arms of men,                                                                        |
|                                                                                                        |                                                                                                                                                                       |
| 시간 매 때마다 그분들은 인간의 팔에 의지하지 않고 고린 가지고 있는 그런                                | but when we turn our hearts to the Lord, and trust in Him, and rely on His arm,                                                                                       |
|                                                                                                        |                                                                                                                                                                       |
| 개인 념이 생이나에 의지지 않고 항상                                                                    | we will truly know that they have received His blessings in this world,                                                                                               |
|                                                                                                        |                                                                                                                                                                       |
| 주님께 의지하며 주님을 신뢰하며 그분께 그분의 도움을 구하는 모습들을 저는                              | even after this world is over, and in this world to come, for eternity. As I testify, I would like to express my deepest gratitude for your hard work and your faith, |
|                                                                                                        |                                                                                                                                                                       |
| 지켜보았습니다이 세상에 그 많은 것들이 저희들에게이 세상의 것에이                                      | and I hope that you will be tired. Jesus is our Christ,                                                                                                               |
|                                                                                                        |                                                                                                                                                                       |
| 사람의 팔에 의지하라고 저희들에게 가르치지만 저희들이 주님께 저의 마음을 돌리고 그분께 신라고 그분을   | and I testify to our Savior, I testify in the name of Jesus Christ, Amen.                                                                                             |
|                                                                                                        |                                                                                                                                                                       |
| 신뢰하고 그분의 팔에 의지할 때 참으로 저희들이이 세상이 끝나고 후에도 영원히 오는이 세상에서 저들이    |                                                                                                                                                                       |
|                                                                                                        |                                                                                                                                                                       |
| 그분의 축복을 받은 사실 간증 드리면서 여러분들의 수고와 여러분들 신앙 사심에 큰 감사를 드리면서        |                                                                                                                                                                       |
|                                                                                                        |                                                                                                                                                                       |
| 여러분이 지치 하식 소망하겠습니다 예수님은 우리들의 그리스도이시며                                     |                                                                                                                                                                       |
|                                                                                                        |                                                                                                                                                                       |
| 저희들의 구세 주님께 간증드립니다 예수 그리스도의 이름으로 간증드립니다 아멘                           |                                                                                                                                                                       |
+--------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
