---
title: "Constrained Living"
author: "DK"
date: "2024-11-04"
draft: yes
categories: [thoughts]
---

There comes a time when one realizes that there are laws or constraints that govern our lives, our society, our universe

Rather than trying to fit the law into our way of living.

We change our lives to fit that constraint.

------------------------------------------------------------------------

Unlike youthful thinking, true freedom is not to have regulations or laws or free from it.

Whether the guidance comes from personal conviction, community standard, religious upbringing, the closer one lives according to this guidance, more fulfilled, happy one will be.

<https://rsc.byu.edu/voice-my-servants/book-mormon-great-answer-great-question>

Most of all, I have been especially struck in rereading and pondering the Book of Mormon with how, for the serious reader, it provides a very, very significant response to what might be called modern man’s architectonic needs—that is, our deep needs to discern some design, purpose, pattern, or plan regarding human existence.

At the center of this architectonic responsiveness, with its related dispensational emphasis, is the Book of Mormon’s steady, Christian core. Jacob wrote, “We knew of Christ . . . many hundred years before his coming; . . . also all the holy prophets which were before us. Behold, they believed in Christ and worshipped the Father in his name, . . . \[keeping\] the law of Moses, it pointing our souls to him” (Jacob 4:4–5). Jacob was emphatic: “None of the prophets have written . . . save they have spoken concerning this Christ” (Jacob 7:11).

Every age needs this architectonic message, but none more desperately than our age, which is preoccupied with skepticism and hedonism: “For how knoweth a man the master whom he has not served, and who is a stranger unto him, and is far from the thoughts and intents of his heart?” (Mosiah 5:13).

He wrote this at an age when most are contemplating retirement.

---

A sacrament speaker talked of several layers of freedom
