---
title: "Sunset, Sunrise"
author: "DK"
date: "2024-09-28"
draft: yes
categories: [promises]
---

Summer months in nothern hemisphere is a time to gather and celebrate.

At times, those gatherings involve couples that are making promises to each other, as well as to God

Also older persons looking back and remembering the time when they made that promise.

Admist the joys of congratulating the couple, meeting your parents or children the other cases one reflects on your own situation a song or two comes to mind and the one from the fiddler on the roof text Anastasia times it is sunrise sunset looking better on life put more appointment car what advice can we get them from each other couple that depicts the song couples flight is how do I love you

Gutke and I married without k really get to know one another but we had a feeling germination to make it work during the marriage I'm sure I didn't but we stay true to the covenant get it through number of experiences like welcoming you members into the family physical challenges what related challenges Leo's economic downturns move we made it God helped God sustain and now looking back truly say that we made important choices thank you thank you happy anniversary dearno

SUNRISE, SUNSET- Fiddler On The Roof- Composed by Jerry Bock, Lyrics by Sheldon Harnick- Broadway Musical 1964

Is this the little girl I carried?\
Is this the little boy at play?\
I don’t remember growing older\
When did they?

When did she get to be a beauty?\
When did he grow to be so tall?\
Wasn’t it yesterday\
When they were small?

**CHORUS 1:**\
Sunrise, sunset\
Sunrise, sunset\
Swiftly flow the days\
Seedlings turn overnight to sunflowers\
Blossoming even as we gaze.\
Sunrise, sunset\
Sunrise, sunset\
Swiftly fly the years\
One season following another\
Laden with happiness and tears.

What words of wisdom can I give them?\
How can I help to ease their way?\
Now they must learn from one another\
Day by day\
They look so natural together\
Just like two newlyweds should be\
Is there a canopy in store for me?

**CHORUS 2:**\
Sunrise, sunset\
Sunrise, sunset\
Swiftly fly the years\
One season following another\
Laden with happiness and tears.

Is this the little girl I carried?\
Is this the little boy at play?\
I don’t remember growing older\
When did they?

When did she get to be a beauty?\
When did he grow to be so tall?\
Wasn’t it yesterday\
When they were small?

**CHORUS 1:**\
Sunrise, sunset\
Sunrise, sunset\
Swiftly flow the days\
Seedlings turn overnight to sunflowers\
Blossoming even as we gaze.\
Sunrise, sunset\
Sunrise, sunset\
Swiftly fly the years\
One season following another\
Laden with happiness and tears.

What words of wisdom can I give them?\
How can I help to ease their way?\
Now they must learn from one another\
Day by day\
They look so natural together\
Just like two newlyweds should be\
Is there a canopy in store for me?

**CHORUS 2:**\
Sunrise, sunset\
Sunrise, sunset\
Swiftly fly the years\
One season following another\
Laden with happiness and tears.

-   
