---
title: "Train People"
author: "DK"
date: "2024-10-03"
draft: yes
categories: [travel]
---

## 2 October 2024

Tokyo - Kyoto

Hikari 507

Kyoto - Tokyo

Hikari 664

Italian/Swiss couple travelling to Kagoshima sat behind us.

An America residing couple with Cotopaxi sat across from us.

Taking their elderly parents around onsens.

## 3 October 2024

Tokyo - Sendai

Komachi 11

Met a family, a Swiss German family, on the Senzan line to Sakunami Onsen

### Unwelcomed at Ichinobo Onsen

On the way up to the onsen, we shared a cab ride, a quick 5 minute ride, for 1400 Yen.

Initially I was cordially welcomed, once the owner/welcome person realized that I only wanted to use the facility for a day, he politely sent me next door – which was closed.

Apparently one needs to book a room to take advantage of onsen offerings

<https://maps.app.goo.gl/ZpQ5Humq2ovhyzjg6>

The lady at the Hiraga Kokeshi Store, through Chan's effort, told us about

[Yunohara Hotel](https://maps.app.goo.gl/ot2XxnWjcL6ZithY8)

Afterwards, we thought about waiting for the hourly bus, but we decided to walk back to the Sakunami Station. A distance of 2.4 km or 1.5 miles. We still beat the bus back to

Sendai - Tokyo

Yamabiko 64

Older lady that spoke some English, she has visited Korea and Taiwan

## 4 October 2024

Tokyo - Kyoto

Hikari 503

Kyoto - Tokyo

Hikari 516

## 5 October 2024

Tokyo - Kanazawa

Kagayaki 507

Kanazawa - Tokyo

Kagayaki 516

Mr. Asuma (東 さん）who has travelled the world, since he works in the supply chain.

He has worked for Costco Japan.

## 6 October 2024

Tokyo - Ofuna

Odoriko-Ito 11

Ofuna - Tokyo

Narita Express 43

## 7 October 2024

Shinjuku - Matsumoto

Azusa 5

[Matsumoto Castle, 松本城](https://maps.app.goo.gl/yv8uWjkEyPDpTJcR7)

Went to Matsumoto Castle, by walking, after taking in some Soba with wild vegetable.

[Krekino Soba Shop](<https://maps.app.goo.gl/CVr8Jp7B4f2r4jjp9>)

We went up as much as we could without missing the bus.

Apparently, the time told by station information office incorrect.

The lady from the City Hall, dropped everything and walked out to the bus station herself.

[Matsumoto City Hall, 松本市役所](https://maps.app.goo.gl/TgswTtMfg9pdtwxbA)

This time we knew ahead time where and whether they would take us.

[Hot Plaza Asama](https://maps.app.goo.gl/XaDRV212Z2tjM1b3A)

Matsumoto - Shinjuku

Azusa 46

## 8 October 2024

Tokyo - Shin Osaka

Hikari 505

Shin Osaka - Hakata

Sakura 563
