---
title: "Rip Van Winkle"
author: "DK"
date: "2023-10-15"
draft: yes
categories: [intro]
---

There was a time when I felt I made a big progress.

Time in Korea

A missionary in LA

\

However, when I returned things had changed and people had made improvements.

\

Matter of how much progress was made

\

What if person left and went at 2019 and returned in 2022.

\

That is what happened in when I received a call to serve on BYU Young Adult Stake.

\

The world and its people are changing

Yet I am stuck in yesterday’s memories

\

Break from it

\

—

\

The interpretation is better than the dream

It seems the side thing is the main thing.

\

Not what life seems to be or appear or dictate but what the meaning you derive from it, based on a firm understanding of who I am, why I am here, and where I want to go

\

Learned some of this from my parents, the stories they told about their lives.

The faith demonstrated.

Enduring to the end

\

By all measures they were simple and not rich as to things of the world

However, they took what was given, accepted it and made best of it.

\

Provided for day to day bread.

Opportunities to gain education.

How to act as a person,

In a family 

In a society

\
\
