---
title: "Audio Appreciation"
author: "DK"
date: "2025-01-05"
draft: yes
resources:
  - 두만강.wav
categories: [music]
---

Family `K` can be grouped into 2.

Those that can considered as singers. And those wished to be included in that group.

Growing up in a society that places high premium on crooners and trot singers, my grandfather K was a popular person.

Unfortunately, my father wasn't part of that group. Instead, in my mother's side, half of her siblings were singers as well as her mother, but not her father.

------------------------------------------------------------------------

My grandfather, 황운학(黃雲鶴), who didn't sing well, at every opportunity would ask his wife to sing.

My maternal grandmother,김연화, sang well. Thus, I was told by mom.

Her go to number was, 눈물젖은 두만강 Tumen River Elegy (圖們江悲歌)

Growing up I never heard her sing, however.

When grandfather was alive, the song was a rendition of a popular song, and a reflection on past relationships.

When grandfather passed away, in his mid 30s, it must have been difficult to hear the song again.

Found a recording of my cousin singing the same song. That cousin and I are same age, born a month apart. Her father was a great singer, like his father was.

Her voice has that quality that takes one back to olden days. A lyrical, story telling quality within her voice.

Hearing the recording, made 25 years, originally recorded on cassette tape, digitally formatted and stored in cloud storage and played through the car's bluetooth made me cry.

***두만강 푸른 물에 노젓는 뱃사공\
흘러간 그 옛날에 내 님을 싣고\
떠나든 그 배는 어데로 갔소\
그리운 내 님이여 그리운 내 님이여\
언제나 오려나***

***On the blue waters of the Tumen River, a boatman rows,\
In those days long past, carrying my beloved.\
Where has that departing boat gone?\
Oh, my dearest one, my dearest one,\
When will you return?***

Made me think of departed ones. Their memories that lingers. Asking the same question,

Korea is a nation of, "...sorrows and acquainted with grief."

Although in recent years, there has been some tremendous growth and spot light in world-wide community.

Those of us that have experienced difficult years, we are still cautious and optimistic.

That someday, we can walk, talk and enjoy our lives in sunlight.

Also, a hope that those things that have been altered, that they will return to its original state.

Innocence, faith, and an order based traditions

<audio controls autoplay loop>

<source src="두만강.wav" type="audio/wav">

Your browser does not support the audio element. </audio>
