---
title: "Fifty Years in US"
author: "DK"
date: "2024-11-22"
draft: yes
categories: [fruits of labor]
---

Growing up I might have spoken Portuguese, Japanese, or Australian or Canadian version of English.

Instead, I learned and spoke the American English and I continue to speak and try to refine my understanding of it.

My father, towards the end of his work engagement in Vietnam, along with his Korean co-workers debated which countries to emigrate to.

Some suggested, Brazil, others thought Australia or Canada. My dad thought about Kyushu area of Japan.

In the end, he and his friends from childhood days, they chose United States of America as their next home.

What should have been a 2 year process took nearly 5 years to complete.

While waiting for the visa to arrive, my father took a job with HanJin.

Our real estate holdings grew in value.

But those 3 extra years gave us time to learn about a new church from United States.

Our family was baptized 3 years prior to leaving for America.

The missionaries that taught the family were mostly from Idaho and Utah.

However, dad's contract was with a company in Greenbelt, MD, AH Smith and Company.

------------------------------------------------------------------------

We went through a typical first generation difficulties.

Due to their hard work, we had means to complete post secondary education.

Though, there was pull to stay close to family.

Went on a mission to the west coast, followed by a move to inter-mountain west.

------------------------------------------------------------------------

Recently, it occurred to me that Sister K and I had been talking in Korean for duration of our marriage.

What seemed uncomfortable and unfamiliar became familiar.

When my parents joined after 20 years of marriage, our dialogues were freer and more in-depth than when I was a teenager, mixing English and forgetting Korean.

10년이면 강산도 변한다 10年になると江山も変わる\
\
출처 : 동양일보(http://www.dynews.co.kr)

Having lived in a country for 5 decades. Still feel like a guest.

Have no home to return to.

Not a family home, it is North Korea.

Not a home with relatives, most ones that know me are no longer.

In Korea, less than 20 people who know my Korean name and who my parents

were.

Back to the beginning.

When Abraham spoke in 1863 in Gettysburg, Pennsylvania, the founding of US was 87 years.

My family arrived in US 50 years ago.

I have a great memory my stay as a sojourner, guest

------------------------------------------------------------------------

Difficulties of learning a language.

How hungry are you\>?

Suzhou, Canton Restaurant.

TN Tan was ordering for us.

He knew the magic code or password.

Most delicious dishes appeared.

Then in one of the nationally recognized gardens, a performance was given.

Another magical spell, didn't know what they were saying.

Maybe I don't need to know.

I wanted to learn this 보통화 (普通话)

I convinced my manager at the time that learning Mandarin was mutually beneficial for the company and for me.

I must have been more persuasive back then.

After 2 semesters, I made progress but not enough to carry on a conversation.

Main hurdles were tones and characters.

------------------------------------------------------------------------

YouTube algorithm found a video about

김원곤 서울대학교 의과대학 명예교수 (ソウル大学医科大学名誉教授)

<https://www.chosun.com/national/weekend/2024/08/17/UCTD7A7NBNGAZEGE5S4YZTJTC4/>

I thought it was a positive thing.

NO, the readers tore him apart.

Why we learn?

To make our lives better

To make other lives better
