---
title: "Wealth of a Society"
author: "DK"
date: "2025-01-26"
draft: yes
categories: [neighborhood]
---

The bishop said that the mother of the speaker had set a new church wrecker wrecker being the furthest travel to hear one's daughter speak at a church meeting speaker as a speaker got up we all took notes and wonder what their how English we were surprised to hear it was her English good it was almost perfect we kept wondering how did she get so good at speaking talked about her life in Korea she mentioned that her scholarship was revoked when she met mentioned it should be serving a 1 1/2 year mission mission car wash to Salt Lake City Temple Square, Mission and while she was serving their shit took part in answering questions from online as she was helping this young man kept raising lotta questions and some of those questions started to factor and she started her own questions after pray and as she was speaking I thought about the wealth of a nation what is it that make each country or society wealthy it is the collective experience and wisdom of a group as well as their commitment and covenant to each other and to God I'm sure none of the people that were attending the church that that day what coerced in any manner to 10 they snow and the young and old especially the older people made their way through the snow and was in attendance I was so delighted to hear her articulate and speak in a manner that was almost like a native so I asked sister cupcake to invite the family and have a dinner with us
