---
title: "BDay Thoughts"
author: "DK"
date: "2024-11-01"
draft: yes
categories: [thoughts]
---

> "...modern man’s architectonic needs—that is, our deep needs to discern some design, purpose, pattern, or plan regarding human existence.''\^\[<https://rsc.byu.edu/voice-my-servants/book-mormon-great-answer-great-question>\]

\-*From an* *Address given on October 10, 1986*

Dictionary defines architectonic as the systematic structure of our knowledge.

------------------------------------------------------------------------

Though we were refugees, a dozen year removed from the Korean War, our family was together.

Furthermore, both my father's and mother's family had clustered around 인천, as their temporary gathering place.

The prevailing thought during the War was that within 3 months, the War will be over and they will return and gather once more in their ancestral homes.

------------------------------------------------------------------------

When we were, thoughts of better world was plentiful food and adequate clothing.

We had no outside influence, just busy surviving day to day.

Grateful that I have had the knowledge about the plan from an early age.

When my mother joined another religion when I was 8.5 years old.

Thank you Elder Maxwell for the message, and clarifying the source of the message, the Book of Mormon

> Every age needs this architectonic message, but none more desperately than our age, which is preoccupied with skepticism and hedonism

\-*Elder Neal A. Maxwell (1926-2004) was a member of the Quorum of the Twelve Apostles. Address at the Book of Mormon Symposium at Brigham Young University on October 10, 1986*

Grateful that I am viewed as I am, or who I should be.

Not as who I am based on where I am from or where I had been.

Neither deference or discrimination based on the stage of life, but based on merit or utility

------------------------------------------------------------------------

At times, I see in a dream, a color image.

The scene is familiar, something of this earth.

However, the light or luminance in this case is something not often nor ever will be seen.

Not ones I have seen.

We live a life of normal, uneventful life, it seems.

However, when the light or the knowledge of the above, or higher being is shown or felt, our lives are transformed.

Enlightment, a state of having knowledge and understanding.
